#!/bin/bash

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0
# Generated by OpenAI GPT-5.6 Sol at 2026-08-21.

set -euo pipefail

usage() {
  printf 'Usage: %s {setup|run_all}\n' "$0"
}

if [[ ! -f VERSION ]]; then
  printf 'ERROR: This script MUST be run from the root of the source tree.\n' >&2
  usage >&2
  exit 1
fi

### Helper functions

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'ERROR: Required command not found: %s\n' "$1" >&2
    exit 69
  fi
}

validate_environment() {
  if [[ "$(uname -s)" != Darwin ]]; then
    printf 'ERROR: This test must run natively on macOS.\n' >&2
    exit 69
  fi
  require_command osascript
  [[ -x /usr/bin/python3 ]] || {
    printf 'ERROR: /usr/bin/python3 is required. Install Xcode Command Line Tools.\n' >&2
    exit 69
  }
}

report_test_event() {
  event=$1
  test_name=$2
  printf 'TEST %s: %s\n' "${event}" "${test_name}"
  printf 'TEST %s: %s\n' "${event}" "${test_name}" >>"${GUI_SCENARIO_ARTIFACTS}/test-results.txt"
}

capture_results() {
  status=$1
  mkdir -p "${GUI_SCENARIO_ARTIFACTS}"
  printf 'exit_code=%d\n' "${status}" >"${GUI_SCENARIO_ARTIFACTS}/result.txt"
  cp -- "${GUI_SCENARIO_WORKDIR}"/obs-*.log "${GUI_SCENARIO_ARTIFACTS}/" 2>/dev/null || true
  cp -R -- "${GUI_SCENARIO_WORKDIR}/Library/Application Support/obs-studio" \
    "${GUI_SCENARIO_ARTIFACTS}/config" 2>/dev/null || true
}

session_cleanup() {
  status=$?
  trap - EXIT
  if ((status != 0)); then
    report_test_event 'RESULT' "${GUI_SCENARIO_TEST_NAME}: FAILED"
  fi
  capture_results "${status}"
  rm -rf -- "${GUI_SCENARIO_WORKDIR}"
  exit "${status}"
}

### Subcommands

setup() {
  validate_environment
}

run_scenario() {
  validate_environment

  build_root="${PLUGIN_BUILD_DIR:-${PWD}}"
  workdir=$(mktemp -d -t obs-backgroundremoval-macos-gui.XXXXXX)
  plugin_root="${workdir}/Library/Application Support/obs-studio/plugins"
  if [[ "${CI+set}" == 'set' ]]; then
    source_plugin_bundle="${HOME:?}/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin"
    [[ -d "${source_plugin_bundle}" ]] || {
      printf 'ERROR: CI plugin bundle was not found: %s\n' "${source_plugin_bundle}" >&2
      exit 69
    }
    mkdir -p "${plugin_root}"
    cp -R -- "${source_plugin_bundle}" "${plugin_root}/obs-backgroundremoval.plugin"
  else
    require_command cmake
    cmake --install "${build_root}/build" --prefix "${workdir}"
  fi
  plugin_bundle="${plugin_root}/obs-backgroundremoval.plugin"
  obs_executable="${OBS_EXECUTABLE:-/Applications/OBS.app/Contents/MacOS/OBS}"

  [[ -x "${obs_executable}" ]] || {
    printf 'ERROR: OBS executable not found: %s\n' "${obs_executable}" >&2
    exit 69
  }
  [[ -x "${plugin_bundle}/Contents/MacOS/obs-backgroundremoval" ]] || {
    printf 'ERROR: Native macOS plugin bundle was not found: %s\n' "${plugin_bundle}" >&2
    printf 'Run bin/bootstrap and bin/build before this scenario test.\n' >&2
    exit 69
  }

  artifacts_root="${build_root}/build_test_reports"
  mkdir -p "${artifacts_root}"
  artifacts_dir=$(mktemp -d \
    "${artifacts_root}/$(date -u +%Y%m%dT%H%M%SZ)-run.XXXXXX")
  printf 'GUI scenario test run directory: %s\n' "${artifacts_dir}"

  export GUI_SCENARIO_ARTIFACTS="${artifacts_dir}"
  export GUI_SCENARIO_OBS_EXECUTABLE="${obs_executable}"
  export GUI_SCENARIO_PLUGIN_ROOT="${plugin_root}"
  export GUI_SCENARIO_SOURCE_DIR="${PWD}"
  export GUI_SCENARIO_TEST_NAME=2000_macos-about-dialog-on-startup.test.py
  export GUI_SCENARIO_TEST_PROGRAM="${PWD}/tests/Scenarios/${GUI_SCENARIO_TEST_NAME}"
  export GUI_SCENARIO_WORKDIR="${workdir}"

  trap session_cleanup EXIT

  report_test_event 'START' "${GUI_SCENARIO_TEST_NAME}"
  printf '%s\n' "${GUI_SCENARIO_TEST_NAME}" >>"${GUI_SCENARIO_ARTIFACTS}/tests.txt"
  /usr/bin/python3 "${GUI_SCENARIO_TEST_PROGRAM}"
  report_test_event 'RESULT' "${GUI_SCENARIO_TEST_NAME}: PASSED"
  printf 'GUI scenario test run passed (1 test).\n'
}

run_all() {
  /bin/bash --noprofile --norc "$0" run_scenario
}

if (($# == 0)); then
  setup
  run_all
  exit 0
fi

case "${1:-}" in
setup)
  shift
  setup "$@"
  exit 0
  ;;
run_all)
  shift
  run_all "$@"
  ;;
run_scenario)
  shift
  run_scenario "$@"
  ;;
--help)
  usage
  exit 0
  ;;
*)
  printf 'ERROR: Unknown subcommand: %s\n' "$1" >&2
  usage >&2
  exit 64
  ;;
esac
