# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0
# Generated by OpenAI GPT-5.6 Sol at 2026-08-21.

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if ($env:OS -ne 'Windows_NT') {
    throw 'This test must run natively on Windows.'
}

$scenarioDir = $PSScriptRoot
$sourceDir = (Resolve-Path (Join-Path $scenarioDir '..\..')).Path
$buildDir = if ($env:PLUGIN_BUILD_DIR) { $env:PLUGIN_BUILD_DIR } else { Join-Path $sourceDir 'build' }
$configuration = if ($env:PLUGIN_CONFIG) { $env:PLUGIN_CONFIG } else { 'RelWithDebInfo' }
$cachePath = Join-Path $buildDir 'CMakeCache.txt'

if (-not (Test-Path -LiteralPath $cachePath -PathType Leaf)) {
    throw "CMakeCache.txt was not found below $buildDir. Configure the project before running this test."
}

$cache = Get-Content -LiteralPath $cachePath
$cmakeCommand = Get-Command cmake -ErrorAction SilentlyContinue
if (-not $cmakeCommand) {
    $cmakePath = ($cache | Where-Object { $_ -like 'CMAKE_COMMAND:INTERNAL=*' } | Select-Object -First 1) `
        -replace '^CMAKE_COMMAND:INTERNAL=', ''
    if (-not $cmakePath -or -not (Test-Path -LiteralPath $cmakePath -PathType Leaf)) {
        throw 'CMake was not found. Add it to PATH or reconfigure the project with an available CMake executable.'
    }
    $cmakeExecutable = (Resolve-Path -LiteralPath $cmakePath).Path
} else {
    $cmakeExecutable = $cmakeCommand.Source
}

& $cmakeExecutable --build $buildDir --config $configuration --target AboutDialogRunner
if ($LASTEXITCODE -ne 0) {
    throw 'Building AboutDialogRunner failed.'
}

$runner = Get-ChildItem -LiteralPath $buildDir -Filter 'AboutDialogRunner.exe' -File -Recurse |
    Where-Object { $_.FullName -match "[\\/]$([regex]::Escape($configuration))[\\/]" } |
    Select-Object -First 1
if (-not $runner) {
    $runner = Get-ChildItem -LiteralPath $buildDir -Filter 'AboutDialogRunner.exe' -File -Recurse |
        Select-Object -First 1
}
if (-not $runner) {
    throw "AboutDialogRunner.exe was not found below $buildDir."
}

$qtDirectory = ($cache | Where-Object { $_ -like 'Qt6_DIR:PATH=*' } | Select-Object -First 1) `
    -replace '^Qt6_DIR:PATH=', ''
if (-not $qtDirectory -or $qtDirectory.EndsWith('-NOTFOUND')) {
    throw 'Qt6_DIR is unavailable in CMakeCache.txt. Reconfigure the project with Qt 6.'
}
$qtPrefix = (Resolve-Path (Join-Path $qtDirectory '..\..\..')).Path
$qtBin = Join-Path $qtPrefix 'bin'
$qtPlugins = Join-Path $qtPrefix 'plugins'
if (-not (Test-Path -LiteralPath (Join-Path $qtBin 'Qt6Core.dll') -PathType Leaf) -or
    -not (Test-Path -LiteralPath (Join-Path $qtPlugins 'platforms\qwindows.dll') -PathType Leaf)) {
    throw "Qt runtime files were not found below $qtPrefix."
}
$env:PATH = "$qtBin;$env:PATH"
$env:QT_PLUGIN_PATH = $qtPlugins

& (Join-Path $scenarioDir '2000_windows-about-dialog.test.ps1') -Runner $runner.FullName
