#!/usr/bin/python3

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0
# Generated by OpenAI GPT-5.6 Sol at 2026-08-21.

import configparser
import os
import shutil
import subprocess
import time
import unittest
from pathlib import Path
from typing import Optional

from helpers.accessibility import find, invoke, is_checked, obs_pid, press_x11_key, process_is_running, text_content, wait_for


ABOUT_TITLE = "About obs-backgroundremoval"
ARTIFACTS = Path(os.environ["GUI_SCENARIO_ARTIFACTS"])
PLUGIN_CONFIG = Path(os.environ["XDG_CONFIG_HOME"]) / "obs-studio/plugin_config/obs-backgroundremoval"
UPDATE_CONFIG = PLUGIN_CONFIG / "update.ini"
UPDATE_TEMP = PLUGIN_CONFIG / "update.ini.tmp"
VERSION = os.environ["GUI_SCENARIO_VERSION"]
WORKDIR = Path(os.environ["GUI_SCENARIO_WORKDIR"])


def report_case(event: str, name: str) -> None:
    message = f"TEST {event}: {name}"
    print(message, flush=True)
    with (ARTIFACTS / "test-results.txt").open("a", encoding="utf-8") as results:
        results.write(f"{message}\n")


class ScenarioTestResult(unittest.TextTestResult):
    def case_name(self, test: unittest.TestCase) -> str:
        return test.shortDescription() or str(test)

    def startTest(self, test: unittest.TestCase) -> None:
        report_case("CASE START", self.case_name(test))
        super().startTest(test)

    def addSuccess(self, test: unittest.TestCase) -> None:
        report_case("CASE RESULT", f"{self.case_name(test)}: PASSED")
        super().addSuccess(test)

    def addFailure(self, test: unittest.TestCase, err) -> None:
        report_case("CASE RESULT", f"{self.case_name(test)}: FAILED")
        super().addFailure(test, err)

    def addError(self, test: unittest.TestCase, err) -> None:
        report_case("CASE RESULT", f"{self.case_name(test)}: FAILED")
        super().addError(test, err)


def stop_obs(process: subprocess.Popen) -> None:
    if process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=10)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait()


def run_obs_phase(phase_name: str, action) -> Path:
    log_path = WORKDIR / f"obs-{phase_name}.log"
    with log_path.open("w", encoding="utf-8") as log:
        process = subprocess.Popen(
            ["obs", "--multi", "--disable-missing-files-check"],
            stdout=log,
            stderr=subprocess.STDOUT,
            text=True,
        )
        os.environ["OBS_PID"] = str(process.pid)
        try:
            action()
        finally:
            stop_obs(process)

    if "[obs-backgroundremoval] Plugin loaded successfully" not in log_path.read_text(encoding="utf-8"):
        raise AssertionError("OBS log does not confirm that obs-backgroundremoval loaded")
    return log_path


def require_descendant(root, description: str, **criteria):
    result = find(root, **criteria)
    if result is None:
        raise AssertionError(f"Missing {description} in {ABOUT_TITLE}")
    return result


def read_update_config() -> configparser.ConfigParser:
    update = configparser.ConfigParser()
    if not update.read(UPDATE_CONFIG, encoding="utf-8"):
        raise AssertionError("Plugin update.ini was not written")
    return update


def verify_acknowledged_version(version: str) -> None:
    update = read_update_config()
    if update.get("update", "version", fallback="") != version:
        raise AssertionError("Plugin update.ini does not contain the current version")


def verify_notification_preference(enabled: bool) -> None:
    update = read_update_config()
    if update.getboolean("update", "check_for_updates", fallback=not enabled) != enabled:
        state = "enabled" if enabled else "disabled"
        raise AssertionError(f"Update notifications were not persisted as {state}")


def initial_run(version: str) -> None:
    pid = obs_pid()
    dialog = wait_for(ABOUT_TITLE, lambda: find(name=ABOUT_TITLE), pid=pid)
    contents = text_content(dialog)
    required_text = (
        "Portrait Background Removal / Virtual Green-screen and Low-Light Enhancement",
        f"Version {version}",
        "Copyright © 2021–2026 Roy Shilkrot",
    )
    for expected in required_text:
        if expected not in contents:
            raise AssertionError(f"Missing visible text {expected!r} in {ABOUT_TITLE}")

    checkbox = require_descendant(
        dialog,
        "update notification checkbox",
        role="check box",
        name="Notify me about new versions on its Filter Properties screen",
    )
    if not is_checked(checkbox):
        raise AssertionError("Update notification checkbox should initially be checked")

    licenses = require_descendant(dialog, "Licenses button", role="button", name="Licenses")
    about_qt = require_descendant(dialog, "About Qt button", role="button", name="About Qt")
    ok = require_descendant(dialog, "OK button", role="button", name="OK")

    invoke(licenses)
    licenses_dialog = wait_for("Licenses dialog", lambda: find(role="dialog", name="Licenses"), pid=pid)
    if "GNU General Public License" not in text_content(licenses_dialog):
        raise AssertionError("Licenses dialog does not expose the expected license text")
    invoke(require_descendant(licenses_dialog, "Close button", role="button", name="Close"))
    wait_for("Licenses dialog to close", lambda: find(role="dialog", name="Licenses") is None, pid=pid)

    invoke(about_qt)
    qt_dialog = wait_for("About Qt dialog", lambda: find(role="alert", name="About Qt"), pid=pid)
    if "Qt" not in text_content(qt_dialog):
        raise AssertionError("About Qt dialog does not expose Qt information")
    close_qt = find(qt_dialog, role="button", name="OK") or find(qt_dialog, role="button", name="Close")
    if close_qt is None:
        raise AssertionError("About Qt dialog has no close action")
    invoke(close_qt)
    wait_for("About Qt dialog to close", lambda: find(role="alert", name="About Qt") is None, pid=pid)

    invoke(checkbox)
    wait_for("update notification checkbox to clear", lambda: not is_checked(checkbox), pid=pid)
    invoke(ok)
    wait_for(f"{ABOUT_TITLE} to close", lambda: find(name=ABOUT_TITLE) is None, pid=pid)
    verify_acknowledged_version(version)
    verify_notification_preference(False)


def repeated_run(absence_seconds: float, context: str = "the same plugin version") -> None:
    pid = obs_pid()
    wait_for("OBS Studio main window", lambda: find(role="frame", name="OBS", contains=True), pid=pid)
    deadline = time.monotonic() + absence_seconds
    while time.monotonic() < deadline:
        if find(name=ABOUT_TITLE) is not None:
            raise AssertionError(f"{ABOUT_TITLE} was unexpectedly shown for {context}")
        if not process_is_running(pid):
            raise RuntimeError("OBS exited during repeated-run verification")
        time.sleep(0.1)


def new_version_run(version: str, expected_notification_preference: Optional[bool] = None) -> None:
    pid = obs_pid()
    dialog = wait_for(ABOUT_TITLE, lambda: find(name=ABOUT_TITLE), pid=pid)
    checkbox = require_descendant(
        dialog,
        "update notification checkbox",
        role="check box",
        name="Notify me about new versions on its Filter Properties screen",
    )
    if expected_notification_preference is not None:
        if is_checked(checkbox) != expected_notification_preference:
            state = "checked" if expected_notification_preference else "clear"
            raise AssertionError(f"Update notification checkbox should be {state}")

    invoke(require_descendant(dialog, "OK button", role="button", name="OK"))
    wait_for(f"{ABOUT_TITLE} to close", lambda: find(name=ABOUT_TITLE) is None, pid=pid)
    verify_acknowledged_version(version)
    if expected_notification_preference is not None:
        verify_notification_preference(expected_notification_preference)


def dismiss_new_version_run(version: str) -> None:
    pid = obs_pid()
    wait_for(ABOUT_TITLE, lambda: find(name=ABOUT_TITLE), pid=pid)
    press_x11_key("Escape")
    wait_for(f"{ABOUT_TITLE} to close", lambda: find(name=ABOUT_TITLE) is None, pid=pid)
    verify_acknowledged_version(version)


def observe_new_version_dialog(version: str) -> None:
    pid = obs_pid()
    wait_for(ABOUT_TITLE, lambda: find(name=ABOUT_TITLE), pid=pid)
    verify_acknowledged_version(version)


def update_config_write_failure() -> None:
    pid = obs_pid()
    dialog = wait_for(ABOUT_TITLE, lambda: find(name=ABOUT_TITLE), pid=pid)
    checkbox = require_descendant(
        dialog,
        "update notification checkbox",
        role="check box",
        name="Notify me about new versions on its Filter Properties screen",
    )
    if is_checked(checkbox):
        raise AssertionError("Update notification checkbox should reflect disabled update.ini state")

    plugin_config = Path(os.environ["XDG_CONFIG_HOME"]) / "obs-studio/plugin_config/obs-backgroundremoval"
    update_path = plugin_config / "update.ini"
    persisted_state = update_path.read_bytes()
    original_mode = plugin_config.stat().st_mode
    plugin_config.chmod(original_mode & ~0o222)
    try:
        invoke(require_descendant(dialog, "OK button", role="button", name="OK"))
        wait_for(f"{ABOUT_TITLE} to close", lambda: find(name=ABOUT_TITLE) is None, pid=pid)
    finally:
        plugin_config.chmod(original_mode)

    if update_path.read_bytes() != persisted_state:
        raise AssertionError("update.ini changed despite the expected notification-setting save failure")


def write_update_config(*lines: str) -> None:
    UPDATE_CONFIG.write_text("\n".join(lines) + "\n", encoding="utf-8")


def remove_update_temp() -> None:
    if UPDATE_TEMP.is_dir():
        UPDATE_TEMP.rmdir()
    else:
        UPDATE_TEMP.unlink(missing_ok=True)


def require_log(log_path: Path, expected: str) -> None:
    if expected not in log_path.read_text(encoding="utf-8"):
        raise AssertionError(f"OBS log does not contain expected update.ini warning: {expected}")


def record_fault(phase_name: str, warning: str) -> None:
    with (ARTIFACTS / "faults.txt").open("a", encoding="utf-8") as faults:
        faults.write(f"{phase_name}: {warning}\n")


def run_update_config_write_failures(phase_name: str, expected_log: str, attempts: int = 2) -> None:
    original_mode = PLUGIN_CONFIG.stat().st_mode
    PLUGIN_CONFIG.chmod(original_mode & ~0o222)
    try:
        log_paths = [
            run_obs_phase(f"{phase_name}-{attempt}", lambda: repeated_run(0.5))
            for attempt in range(1, attempts + 1)
        ]
    finally:
        PLUGIN_CONFIG.chmod(original_mode)
    for attempt, log_path in enumerate(log_paths, start=1):
        require_log(log_path, expected_log)
        record_fault(f"{phase_name}-{attempt}", expected_log)


def repair_update_state(phase_name: str, contents: bytes) -> None:
    UPDATE_CONFIG.write_bytes(contents)
    run_obs_phase(f"{phase_name}-repair", lambda: new_version_run(VERSION))
    run_obs_phase(f"{phase_name}-repeat", lambda: repeated_run(0.5))


class LinuxAboutDialogOnStartupTest(unittest.TestCase):
    def test_100_initial_actions(self) -> None:
        """ST-2000.1-ST-2000.4 about-dialog-on-startup-initial-actions"""
        run_obs_phase("about-dialog-on-startup-initial", lambda: initial_run(VERSION))

    def test_200_same_version_absent(self) -> None:
        """ST-2000.5 about-dialog-on-startup-same-version-absent"""
        run_obs_phase("about-dialog-on-startup-repeat", lambda: repeated_run(0.5))
        shutil.copy2(UPDATE_CONFIG, ARTIFACTS / "update-normal.ini")

    def test_300_new_version_visible(self) -> None:
        """ST-2000.6 about-dialog-on-startup-new-version-visible"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        run_obs_phase(
            "about-dialog-on-startup-new-version",
            lambda: new_version_run(VERSION, expected_notification_preference=False),
        )

    def test_400_notification_save_failure(self) -> None:
        """ST-2000.7 about-dialog-on-startup-notification-save-failure"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        log_path = run_obs_phase("about-dialog-on-startup-notification-save-failure", update_config_write_failure)
        warning = "[obs-backgroundremoval] Failed to save update config"
        require_log(log_path, warning)
        shutil.copy2(UPDATE_CONFIG, ARTIFACTS / "update-notification-save-failure.ini")
        record_fault("about-dialog-on-startup-notification-save-failure", warning)

    def test_500_update_open_failure(self) -> None:
        """ST-2000.8 about-dialog-on-startup-update-open-failure"""
        UPDATE_CONFIG.unlink(missing_ok=True)
        run_update_config_write_failures(
            "about-dialog-on-startup-update-open-failure",
            "[obs-backgroundremoval] Failed to open update config",
        )
        self.assertFalse(UPDATE_CONFIG.exists(), "update.ini was unexpectedly created in a read-only directory")

    def test_600_update_save_failure(self) -> None:
        """ST-2000.9 about-dialog-on-startup-update-save-failure"""
        write_update_config("[update]", "version=0.0.0")
        run_update_config_write_failures(
            "about-dialog-on-startup-update-save-failure",
            "[obs-backgroundremoval] Failed to save update config",
        )
        self.assertIn(
            "version=0.0.0",
            UPDATE_CONFIG.read_text(encoding="utf-8"),
            "update.ini changed despite the expected save failure",
        )

    def test_700_unwritable_temporary_file(self) -> None:
        """ST-2000.10 about-dialog-on-startup-unwritable-temporary-file"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        UPDATE_TEMP.write_text("stale temporary state\n", encoding="utf-8")
        original_mode = UPDATE_TEMP.stat().st_mode
        UPDATE_TEMP.chmod(original_mode & ~0o222)
        try:
            for attempt in range(1, 3):
                phase = f"about-dialog-on-startup-unwritable-temporary-file-{attempt}"
                log_path = run_obs_phase(phase, lambda: repeated_run(0.5))
                warning = "[obs-backgroundremoval] Failed to save update config"
                require_log(log_path, warning)
                record_fault(phase, warning)
        finally:
            UPDATE_TEMP.chmod(original_mode)
            remove_update_temp()
        self.assertIn("version=0.0.0", UPDATE_CONFIG.read_text(encoding="utf-8"))

    def test_710_temporary_directory_and_recovery(self) -> None:
        """ST-2000.11-ST-2000.12 about-dialog-on-startup-temporary-directory-and-recovery"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        remove_update_temp()
        UPDATE_TEMP.mkdir()
        try:
            for attempt in range(1, 3):
                phase = f"about-dialog-on-startup-temporary-directory-{attempt}"
                log_path = run_obs_phase(phase, lambda: repeated_run(0.5))
                warning = "[obs-backgroundremoval] Failed to save update config"
                require_log(log_path, warning)
                record_fault(phase, warning)
        finally:
            remove_update_temp()

        self.assertIn("version=0.0.0", UPDATE_CONFIG.read_text(encoding="utf-8"))
        run_obs_phase("about-dialog-on-startup-storage-recovered", lambda: new_version_run(VERSION))
        run_obs_phase("about-dialog-on-startup-storage-recovered-repeat", lambda: repeated_run(0.5))

    def test_720_empty_update_state(self) -> None:
        """ST-2000.13 about-dialog-on-startup-empty-update-state"""
        repair_update_state("about-dialog-on-startup-empty-update-state", b"")

    def test_730_missing_update_section(self) -> None:
        """ST-2000.14 about-dialog-on-startup-missing-update-section"""
        repair_update_state("about-dialog-on-startup-missing-update-section", b"[other]\nversion=0.0.0\n")

    def test_740_missing_version(self) -> None:
        """ST-2000.15 about-dialog-on-startup-missing-version"""
        repair_update_state("about-dialog-on-startup-missing-version", b"[update]\ncheck_for_updates=false\n")

    def test_750_truncated_update_state(self) -> None:
        """ST-2000.16 about-dialog-on-startup-truncated-update-state"""
        repair_update_state("about-dialog-on-startup-truncated-update-state", b"[update\nversion=0.0.0\n")

    def test_760_invalid_update_state_bytes(self) -> None:
        """ST-2000.17 about-dialog-on-startup-invalid-update-state-bytes"""
        repair_update_state("about-dialog-on-startup-invalid-update-state-bytes", b"\xff\xfe\x00invalid\n")

    def test_770_dismiss_without_ok(self) -> None:
        """ST-2000.18 about-dialog-on-startup-dismiss-without-ok"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        run_obs_phase("about-dialog-on-startup-dismiss-without-ok", lambda: dismiss_new_version_run(VERSION))
        run_obs_phase("about-dialog-on-startup-dismiss-without-ok-repeat", lambda: repeated_run(0.5))

    def test_780_exit_while_dialog_visible(self) -> None:
        """ST-2000.19 about-dialog-on-startup-exit-while-dialog-visible"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        run_obs_phase("about-dialog-on-startup-exit-while-dialog-visible", lambda: observe_new_version_dialog(VERSION))
        run_obs_phase("about-dialog-on-startup-exit-while-dialog-visible-repeat", lambda: repeated_run(0.5))

    def test_800_downgrade_visible_once(self) -> None:
        """ST-2000.20 about-dialog-on-startup-downgrade-visible-once"""
        future_version = "9999.0.0"
        write_update_config("[update]", f"version={future_version}", "check_for_updates=false")
        run_obs_phase("about-dialog-on-startup-downgrade", lambda: new_version_run(VERSION))
        run_obs_phase("about-dialog-on-startup-downgrade-repeat", lambda: repeated_run(0.5))


def main() -> None:
    suite = unittest.defaultTestLoader.loadTestsFromTestCase(LinuxAboutDialogOnStartupTest)
    with (ARTIFACTS / "unittest.txt").open("w", encoding="utf-8") as unittest_output:
        result = unittest.TextTestRunner(
            stream=unittest_output,
            verbosity=2,
            failfast=True,
            resultclass=ScenarioTestResult,
        ).run(suite)

    if result.wasSuccessful():
        print("About dialog GUI scenario passed.", flush=True)
    raise SystemExit(not result.wasSuccessful())


if __name__ == "__main__":
    main()
