#!/usr/bin/python3

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0
# Generated by OpenAI GPT-5.6 Sol at 2026-08-21.

import configparser
import os
import signal
import shutil
import subprocess
import time
import unittest
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional


ABOUT_TITLE = "About obs-backgroundremoval"
ABSENCE_VERIFICATION_SECONDS = 2.0
POLL_INTERVAL_SECONDS = 0.05
OBS_EXECUTABLE = Path(os.environ["GUI_SCENARIO_OBS_EXECUTABLE"])
PLUGIN_ROOT = Path(os.environ["GUI_SCENARIO_PLUGIN_ROOT"])
SOURCE_DIR = Path(os.environ["GUI_SCENARIO_SOURCE_DIR"])
VERSION = (SOURCE_DIR / "VERSION").read_text(encoding="utf-8").strip()
WORKDIR = Path(os.environ["GUI_SCENARIO_WORKDIR"])
ARTIFACTS = Path(os.environ["GUI_SCENARIO_ARTIFACTS"])
CONFIG_ROOT = WORKDIR / "Library/Application Support/obs-studio"
PLUGIN_CONFIG = CONFIG_ROOT / "plugin_config/obs-backgroundremoval"
UPDATE_CONFIG = PLUGIN_CONFIG / "update.ini"
UPDATE_TEMP = PLUGIN_CONFIG / "update.ini.tmp"
PROFILE_DIR = CONFIG_ROOT / "basic/profiles/obs-backgroundremoval-dev-720p"
PLUGIN_MANAGER_DIR = CONFIG_ROOT / "plugin_manager"

@dataclass
class OBSProcess:
    pid: int
    launcher: subprocess.Popen

    def poll(self) -> Optional[int]:
        return self.launcher.poll()


CURRENT_PROCESS: Optional[OBSProcess] = None
CURRENT_LOG_PATH: Optional[Path] = None


def run_osa(source: str, *arguments: str) -> str:
    result = subprocess.run(
        ["/usr/bin/osascript", "-", *arguments],
        input=source,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "osascript failed")
    return result.stdout.strip()


def process_script(body: str) -> str:
    return f"""
on run arguments
  set targetPid to (item 1 of arguments) as integer
  tell application "System Events"
    set targetProcess to first application process whose unix id is targetPid
    {body}
  end tell
end run
"""


def window_exists(pid: int, title: str) -> bool:
    return run_osa(
        process_script("return exists window (item 2 of arguments) of targetProcess"),
        str(pid), title,
    ) == "true"


def wait_for(description: str, predicate: Callable[[], bool], timeout: float = 30.0) -> None:
    deadline = time.monotonic() + timeout
    last_error: Optional[Exception] = None
    while time.monotonic() < deadline:
        try:
            if predicate():
                return
        except RuntimeError as error:
            last_error = error
        time.sleep(POLL_INTERVAL_SECONDS)
    detail = f": {last_error}" if last_error else ""
    raise AssertionError(f"Timed out waiting for {description}{detail}")


def window_text(pid: int, title: str) -> str:
    return run_osa(
        process_script("""
set targetWindow to window (item 2 of arguments) of targetProcess
set output to ""
repeat with textElement in every static text of targetWindow
  try
    set output to output & (name of textElement as text) & linefeed
  end try
end repeat
repeat with textElement in every text area of targetWindow
  try
    set output to output & (value of textElement as text) & linefeed
  end try
end repeat
return output
"""), str(pid), title,
    )


def group_button_exists(pid: int, title: str, label: str) -> bool:
    return run_osa(
        process_script("""
tell group 1 of window (item 2 of arguments) of targetProcess
  return exists button (item 3 of arguments)
end tell
"""), str(pid), title, label,
    ) == "true"


def click_group_button(pid: int, title: str, label: str) -> None:
    run_osa(
        process_script("""
tell group 1 of window (item 2 of arguments) of targetProcess
  click button (item 3 of arguments)
end tell
"""), str(pid), title, label,
    )


def qt_dialog_exists(pid: int) -> bool:
    return run_osa(
        process_script("""
try
  return name of static text 1 of window 1 of targetProcess contains "About Qt"
on error
  return false
end try
"""), str(pid),
    ) == "true"


def qt_dialog_text(pid: int) -> str:
    return run_osa(
        process_script("""
set output to ""
repeat with textElement in every static text of window 1 of targetProcess
  try
    set output to output & (name of textElement as text) & linefeed
  end try
end repeat
return output
"""), str(pid),
    )


def close_qt_dialog(pid: int) -> None:
    run_osa(
        process_script('click button "OK" of group 1 of window 1 of targetProcess'),
        str(pid),
    )


def checkbox_checked(pid: int) -> bool:
    return run_osa(
        process_script(f'return value of checkbox 1 of window "{ABOUT_TITLE}" of targetProcess as boolean'),
        str(pid),
    ) == "true"


def checkbox_details(pid: int) -> str:
    return run_osa(
        process_script(
            f'return {{name, value, role description, description}} of checkbox 1 of window "{ABOUT_TITLE}" of targetProcess'
        ),
        str(pid),
    )


def click_checkbox(pid: int) -> None:
    run_osa(
        process_script(f'click checkbox 1 of window "{ABOUT_TITLE}" of targetProcess'),
        str(pid),
    )


def close_window(pid: int, title: str) -> None:
    run_osa(
        process_script("""
set closeButton to first button of window (item 2 of arguments) of targetProcess whose subrole is "AXCloseButton"
perform action "AXPress" of closeButton
"""), str(pid), title,
    )


def obs_process_ids() -> set[int]:
    output = run_osa(
        'tell application "System Events" to return unix id of every application process whose name is "OBS"'
    )
    return {int(pid.strip()) for pid in output.split(",") if pid.strip()}


def launch_obs(log_path: Path, environment: dict[str, str]) -> OBSProcess:
    existing_pids = obs_process_ids()
    command = [
        "/usr/bin/open", "-n", "-W",
        "-o", str(log_path), "--stderr", str(log_path),
    ]
    for name in ("CFFIXED_USER_HOME", "HOME"):
        command.extend(("--env", f"{name}={environment[name]}"))
    command.extend((
        str(OBS_EXECUTABLE.parent.parent.parent),
        "--args", "--multi", "--disable-missing-files-check", "--disable-updater",
    ))
    launcher = subprocess.Popen(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    def launched_pid() -> Optional[int]:
        new_pids = obs_process_ids() - existing_pids
        if len(new_pids) == 1:
            return new_pids.pop()
        if len(new_pids) > 1:
            raise RuntimeError(f"Multiple new OBS processes appeared: {sorted(new_pids)}")
        if launcher.poll() is not None:
            _, stderr = launcher.communicate()
            raise RuntimeError(stderr.strip() or "open exited before OBS launched")
        return None

    launched_pids: list[int] = []

    def capture_launched_pid() -> bool:
        pid = launched_pid()
        if pid is None:
            return False
        launched_pids.append(pid)
        return True

    try:
        wait_for("OBS process to launch", capture_launched_pid)
    except BaseException:
        for pid in obs_process_ids() - existing_pids:
            try:
                os.kill(pid, signal.SIGTERM)
            except ProcessLookupError:
                pass
        if launcher.poll() is None:
            launcher.terminate()
            try:
                launcher.wait(timeout=5)
            except subprocess.TimeoutExpired:
                launcher.kill()
                launcher.wait(timeout=5)
        raise
    return OBSProcess(pid=launched_pids[0], launcher=launcher)


def stop_launcher(launcher: subprocess.Popen) -> None:
    if launcher.poll() is not None:
        return
    launcher.terminate()
    try:
        launcher.wait(timeout=5)
    except subprocess.TimeoutExpired:
        launcher.kill()
        launcher.wait(timeout=5)


def stop_obs(process: OBSProcess) -> None:
    if process.poll() is not None:
        return
    try:
        os.kill(process.pid, signal.SIGTERM)
    except ProcessLookupError:
        stop_launcher(process.launcher)
        return
    try:
        process.launcher.wait(timeout=5)
    except subprocess.TimeoutExpired:
        try:
            os.kill(process.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
        stop_launcher(process.launcher)


def diagnostic_command(*command: str, input_text: Optional[str] = None) -> str:
    try:
        result = subprocess.run(
            command,
            input=input_text,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
            timeout=20,
        )
        return f"$ {' '.join(command)}\nexit_code={result.returncode}\n{result.stdout}"
    except BaseException as error:
        return f"$ {' '.join(command)}\nfailed: {error!r}\n"


def capture_obs_diagnostics(process: OBSProcess, phase_name: str) -> None:
    diagnostics_path = ARTIFACTS / f"obs-{phase_name}-diagnostics.txt"
    screenshot_path = ARTIFACTS / f"obs-{phase_name}-screen.png"
    sections = [
        (
            f"pid={process.pid}\n"
            f"launcher_pid={process.launcher.pid}\n"
            f"launcher_status={process.launcher.poll()}\n"
            f"obs_executable={OBS_EXECUTABLE}\n"
            f"plugin_root={PLUGIN_ROOT}\n"
        ),
        diagnostic_command(
            "/bin/ps", "-p", str(process.pid), "-o", "pid=,ppid=,state=,etime=,command="
        ),
        diagnostic_command(
            "/usr/bin/osascript", "-", str(process.pid),
            input_text=process_script("return name of every window of targetProcess"),
        ),
        diagnostic_command(
            "/usr/bin/osascript", "-", str(process.pid),
            input_text=process_script(
                "return {name, frontmost, visible, unix id} of targetProcess"
            ),
        ),
        diagnostic_command(
            "/usr/bin/log", "show", "--last", "2m", "--style", "compact",
            "--predicate", f"processIdentifier == {process.pid}",
        ),
        diagnostic_command("/usr/sbin/screencapture", "-x", str(screenshot_path)),
    ]
    diagnostics_path.write_text("\n=====\n".join(sections), encoding="utf-8")


def capture_launcher_output(process: OBSProcess, phase_name: str) -> None:
    try:
        stdout, stderr = process.launcher.communicate(timeout=1)
        status = process.launcher.returncode
        contents = f"exit_code={status}\n===== stdout =====\n{stdout}\n===== stderr =====\n{stderr}"
    except BaseException as error:
        contents = f"failed: {error!r}\n"
    (ARTIFACTS / f"obs-{phase_name}-launcher.txt").write_text(contents, encoding="utf-8")


def run_obs_phase(phase_name: str, action: Callable[[OBSProcess], None]) -> Path:
    global CURRENT_LOG_PATH, CURRENT_PROCESS
    log_path = WORKDIR / f"obs-{phase_name}.log"
    CURRENT_LOG_PATH = log_path
    environment = os.environ.copy()
    environment.update({
        "CFFIXED_USER_HOME": str(WORKDIR),
        "HOME": str(WORKDIR),
    })
    process = launch_obs(log_path, environment)
    CURRENT_PROCESS = process
    try:
        try:
            action(process)
        except BaseException:
            capture_obs_diagnostics(process, phase_name)
            raise
    finally:
        try:
            stop_obs(process)
        finally:
            capture_launcher_output(process, phase_name)
            CURRENT_PROCESS = None
            CURRENT_LOG_PATH = None
    if "[obs-backgroundremoval] Plugin loaded successfully" not in log_path.read_text(encoding="utf-8"):
        raise AssertionError("OBS log does not confirm that obs-backgroundremoval loaded")
    return log_path


def read_config(path: Path) -> configparser.ConfigParser:
    config = configparser.ConfigParser()
    if not config.read(path, encoding="utf-8"):
        raise AssertionError(f"Config was not written: {path}")
    return config


def verify_acknowledged_version(version: str) -> None:
    update = read_config(UPDATE_CONFIG)
    if update.get("update", "version", fallback="") != version:
        raise AssertionError("Plugin update.ini does not contain the current version")


def verify_notification_preference(enabled: bool) -> None:
    update = read_config(UPDATE_CONFIG)
    if update.getboolean("update", "check_for_updates", fallback=not enabled) != enabled:
        state = "enabled" if enabled else "disabled"
        raise AssertionError(f"Update notifications were not persisted as {state}")


def initial_run(process: OBSProcess) -> None:
    pid = process.pid
    wait_for(ABOUT_TITLE, lambda: window_exists(pid, ABOUT_TITLE))
    contents = window_text(pid, ABOUT_TITLE)
    for expected in (
        "Portrait Background Removal / Virtual Green-screen and Low-Light Enhancement",
        f"Version {VERSION}",
        "Copyright © 2021–2026 Roy Shilkrot",
    ):
        if expected not in contents:
            raise AssertionError(f"Missing visible text {expected!r} in {ABOUT_TITLE}")
    if not checkbox_checked(pid):
        raise AssertionError("Update notification checkbox should initially be checked")
    for label in ("Licenses", "About Qt", "OK"):
        if not group_button_exists(pid, ABOUT_TITLE, label):
            raise AssertionError(f"Missing {label} button in {ABOUT_TITLE}")

    click_group_button(pid, ABOUT_TITLE, "Licenses")
    wait_for("Licenses dialog", lambda: window_exists(pid, "Licenses"))
    if "GNU General Public License" not in window_text(pid, "Licenses"):
        raise AssertionError("Licenses dialog does not expose the expected license text")
    click_group_button(pid, "Licenses", "Close")
    wait_for("Licenses dialog to close", lambda: not window_exists(pid, "Licenses"))

    click_group_button(pid, ABOUT_TITLE, "About Qt")
    wait_for("About Qt dialog", lambda: qt_dialog_exists(pid))
    if "Qt" not in qt_dialog_text(pid):
        raise AssertionError("About Qt dialog does not expose Qt information")
    close_qt_dialog(pid)
    wait_for("About Qt dialog to close", lambda: not qt_dialog_exists(pid))

    click_checkbox(pid)
    wait_for("update notification checkbox to clear", lambda: not checkbox_checked(pid))
    click_group_button(pid, ABOUT_TITLE, "OK")
    wait_for(f"{ABOUT_TITLE} to close", lambda: not window_exists(pid, ABOUT_TITLE))
    verify_acknowledged_version(VERSION)
    verify_notification_preference(False)


def repeated_run(
    process: OBSProcess,
    absence_seconds: float = ABSENCE_VERIFICATION_SECONDS,
) -> None:
    pid = process.pid
    wait_for("OBS Studio main window", lambda: run_osa(
        process_script('return exists (first window of targetProcess whose name contains "OBS")'), str(pid)
    ) == "true")
    if CURRENT_LOG_PATH is None:
        raise RuntimeError("OBS log path is unavailable")
    wait_for(
        "OBS startup to complete",
        lambda: "==== Startup complete" in CURRENT_LOG_PATH.read_text(encoding="utf-8"),
    )
    deadline = time.monotonic() + absence_seconds
    while time.monotonic() < deadline:
        if window_exists(pid, ABOUT_TITLE):
            raise AssertionError(f"{ABOUT_TITLE} was unexpectedly shown")
        if process.poll() is not None:
            raise RuntimeError("OBS exited during repeated-run verification")
        time.sleep(POLL_INTERVAL_SECONDS)


def accept_new_version(process: OBSProcess, expected_notification_preference: Optional[bool] = None) -> None:
    pid = process.pid
    wait_for(ABOUT_TITLE, lambda: window_exists(pid, ABOUT_TITLE))
    if expected_notification_preference is not None:
        if checkbox_checked(pid) != expected_notification_preference:
            state = "checked" if expected_notification_preference else "clear"
            persisted = read_config(UPDATE_CONFIG).get("update", "check_for_updates", fallback="<missing>")
            raise AssertionError(
                f"Update notification checkbox should be {state}; persisted value is {persisted!r}; "
                f"accessibility element is {checkbox_details(pid)!r}"
            )
    click_group_button(pid, ABOUT_TITLE, "OK")
    wait_for(f"{ABOUT_TITLE} to close", lambda: not window_exists(pid, ABOUT_TITLE))
    verify_acknowledged_version(VERSION)
    if expected_notification_preference is not None:
        verify_notification_preference(expected_notification_preference)


def dismiss_new_version_run(process: OBSProcess) -> None:
    wait_for(ABOUT_TITLE, lambda: window_exists(process.pid, ABOUT_TITLE))
    close_window(process.pid, ABOUT_TITLE)
    wait_for(f"{ABOUT_TITLE} to close", lambda: not window_exists(process.pid, ABOUT_TITLE))
    verify_acknowledged_version(VERSION)


def observe_new_version_dialog(process: OBSProcess) -> None:
    wait_for(ABOUT_TITLE, lambda: window_exists(process.pid, ABOUT_TITLE))
    verify_acknowledged_version(VERSION)


def write_update_config(*lines: str) -> None:
    UPDATE_CONFIG.write_text("\n".join(lines) + "\n", encoding="utf-8")


def remove_update_temp() -> None:
    if UPDATE_TEMP.is_dir():
        UPDATE_TEMP.rmdir()
    else:
        UPDATE_TEMP.unlink(missing_ok=True)


def require_log(log_path: Path, expected: str) -> None:
    if expected not in log_path.read_text(encoding="utf-8"):
        raise AssertionError(f"OBS log does not contain expected warning: {expected}")


def record_fault(phase_name: str, warning: str) -> None:
    with (ARTIFACTS / "faults.txt").open("a", encoding="utf-8") as faults:
        faults.write(f"{phase_name}: {warning}\n")


def update_config_write_failure(process: OBSProcess) -> None:
    pid = process.pid
    wait_for(ABOUT_TITLE, lambda: window_exists(pid, ABOUT_TITLE))
    if checkbox_checked(pid):
        raise AssertionError("Update notification checkbox should reflect disabled update.ini state")
    persisted_state = UPDATE_CONFIG.read_bytes()
    original_mode = PLUGIN_CONFIG.stat().st_mode
    PLUGIN_CONFIG.chmod(original_mode & ~0o222)
    try:
        click_group_button(pid, ABOUT_TITLE, "OK")
        wait_for(f"{ABOUT_TITLE} to close", lambda: not window_exists(pid, ABOUT_TITLE))
    finally:
        PLUGIN_CONFIG.chmod(original_mode)
    if process.poll() is not None:
        raise AssertionError("OBS exited after the notification-setting save failure")
    if UPDATE_CONFIG.read_bytes() != persisted_state:
        raise AssertionError("update.ini changed despite the expected notification-setting save failure")


def run_update_config_write_failures(phase_name: str, expected_log: str) -> None:
    original_mode = PLUGIN_CONFIG.stat().st_mode
    PLUGIN_CONFIG.chmod(original_mode & ~0o222)
    try:
        logs = [run_obs_phase(f"{phase_name}-{attempt}", repeated_run) for attempt in (1, 2)]
    finally:
        PLUGIN_CONFIG.chmod(original_mode)
    for attempt, log_path in enumerate(logs, start=1):
        require_log(log_path, expected_log)
        record_fault(f"{phase_name}-{attempt}", expected_log)


def repair_update_state(phase_name: str, contents: bytes) -> None:
    UPDATE_CONFIG.write_bytes(contents)
    run_obs_phase(f"{phase_name}-repair", accept_new_version)
    run_obs_phase(f"{phase_name}-repeat", repeated_run)


class MacOSAboutDialogOnStartupTest(unittest.TestCase):
    def test_100_initial_actions(self) -> None:
        """ST-2000.1-ST-2000.4 about-dialog-on-startup-initial-actions"""
        run_obs_phase("about-dialog-on-startup-initial", initial_run)

    def test_200_same_version_absent(self) -> None:
        """ST-2000.5 about-dialog-on-startup-same-version-absent"""
        run_obs_phase("about-dialog-on-startup-repeat", repeated_run)
        shutil.copy2(UPDATE_CONFIG, ARTIFACTS / "update-normal.ini")

    def test_300_new_version_visible(self) -> None:
        """ST-2000.6 about-dialog-on-startup-new-version-visible"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        run_obs_phase(
            "about-dialog-on-startup-new-version",
            lambda process: accept_new_version(process, False),
        )

    def test_400_notification_save_failure(self) -> None:
        """ST-2000.7 about-dialog-on-startup-notification-save-failure"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        log_path = run_obs_phase("about-dialog-on-startup-notification-save-failure", update_config_write_failure)
        warning = "[obs-backgroundremoval] Failed to save the update notification setting to update.ini"
        require_log(log_path, warning)
        shutil.copy2(UPDATE_CONFIG, ARTIFACTS / "update-notification-save-failure.ini")
        record_fault("about-dialog-on-startup-notification-save-failure", warning)

    def test_500_update_open_failure(self) -> None:
        """ST-2000.8 about-dialog-on-startup-update-open-failure"""
        UPDATE_CONFIG.unlink(missing_ok=True)
        run_update_config_write_failures(
            "about-dialog-on-startup-update-open-failure",
            "Failed to open update config",
        )
        self.assertFalse(UPDATE_CONFIG.exists())

    def test_600_update_save_failure(self) -> None:
        """ST-2000.9 about-dialog-on-startup-update-save-failure"""
        write_update_config("[update]", "version=0.0.0")
        run_update_config_write_failures(
            "about-dialog-on-startup-update-save-failure",
            "Failed to save update config",
        )
        self.assertIn("version=0.0.0", UPDATE_CONFIG.read_text(encoding="utf-8"))

    def test_700_unwritable_temporary_file(self) -> None:
        """ST-2000.10 about-dialog-on-startup-unwritable-temporary-file"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        UPDATE_TEMP.write_text("stale temporary state\n", encoding="utf-8")
        original_mode = UPDATE_TEMP.stat().st_mode
        UPDATE_TEMP.chmod(original_mode & ~0o222)
        try:
            for attempt in (1, 2):
                phase = f"about-dialog-on-startup-unwritable-temporary-file-{attempt}"
                log_path = run_obs_phase(phase, repeated_run)
                warning = "Failed to save update config"
                require_log(log_path, warning)
                record_fault(phase, warning)
        finally:
            UPDATE_TEMP.chmod(original_mode)
            remove_update_temp()
        self.assertIn("version=0.0.0", UPDATE_CONFIG.read_text(encoding="utf-8"))

    def test_710_temporary_directory_and_recovery(self) -> None:
        """ST-2000.11-ST-2000.12 about-dialog-on-startup-temporary-directory-and-recovery"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        remove_update_temp()
        UPDATE_TEMP.mkdir()
        try:
            for attempt in (1, 2):
                phase = f"about-dialog-on-startup-temporary-directory-{attempt}"
                log_path = run_obs_phase(phase, repeated_run)
                warning = "Failed to save update config"
                require_log(log_path, warning)
                record_fault(phase, warning)
        finally:
            remove_update_temp()
        self.assertIn("version=0.0.0", UPDATE_CONFIG.read_text(encoding="utf-8"))
        run_obs_phase("about-dialog-on-startup-storage-recovered", accept_new_version)
        run_obs_phase("about-dialog-on-startup-storage-recovered-repeat", repeated_run)

    def test_720_empty_update_state(self) -> None:
        """ST-2000.13 about-dialog-on-startup-empty-update-state"""
        repair_update_state("about-dialog-on-startup-empty-update-state", b"")

    def test_730_missing_update_section(self) -> None:
        """ST-2000.14 about-dialog-on-startup-missing-update-section"""
        repair_update_state("about-dialog-on-startup-missing-update-section", b"[other]\nversion=0.0.0\n")

    def test_740_missing_version(self) -> None:
        """ST-2000.15 about-dialog-on-startup-missing-version"""
        repair_update_state("about-dialog-on-startup-missing-version", b"[update]\ncheck_for_updates=false\n")

    def test_750_truncated_update_state(self) -> None:
        """ST-2000.16 about-dialog-on-startup-truncated-update-state"""
        repair_update_state("about-dialog-on-startup-truncated-update-state", b"[update\nversion=0.0.0\n")

    def test_760_invalid_update_state_bytes(self) -> None:
        """ST-2000.17 about-dialog-on-startup-invalid-update-state-bytes"""
        repair_update_state("about-dialog-on-startup-invalid-update-state-bytes", b"\xff\xfe\x00invalid\n")

    def test_770_dismiss_without_ok(self) -> None:
        """ST-2000.18 about-dialog-on-startup-dismiss-without-ok"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        run_obs_phase("about-dialog-on-startup-dismiss-without-ok", dismiss_new_version_run)
        run_obs_phase("about-dialog-on-startup-dismiss-without-ok-repeat", repeated_run)

    def test_780_exit_while_dialog_visible(self) -> None:
        """ST-2000.19 about-dialog-on-startup-exit-while-dialog-visible"""
        write_update_config("[update]", "version=0.0.0", "check_for_updates=false")
        run_obs_phase("about-dialog-on-startup-exit-while-dialog-visible", observe_new_version_dialog)
        run_obs_phase("about-dialog-on-startup-exit-while-dialog-visible-repeat", repeated_run)

    def test_800_downgrade_visible_once(self) -> None:
        """ST-2000.20 about-dialog-on-startup-downgrade-visible-once"""
        write_update_config("[update]", "version=9999.0.0", "check_for_updates=false")
        run_obs_phase("about-dialog-on-startup-downgrade", accept_new_version)
        run_obs_phase("about-dialog-on-startup-downgrade-repeat", repeated_run)


class ScenarioTestResult(unittest.TextTestResult):
    def startTest(self, test: unittest.TestCase) -> None:
        print(f"TEST CASE START: {test.shortDescription() or test}", flush=True)
        super().startTest(test)

    def addSuccess(self, test: unittest.TestCase) -> None:
        print(f"TEST CASE RESULT: {test.shortDescription() or test}: PASSED", flush=True)
        super().addSuccess(test)

    def addFailure(self, test: unittest.TestCase, err) -> None:
        print(f"TEST CASE RESULT: {test.shortDescription() or test}: FAILED", flush=True)
        super().addFailure(test, err)

    def addError(self, test: unittest.TestCase, err) -> None:
        print(f"TEST CASE RESULT: {test.shortDescription() or test}: FAILED", flush=True)
        super().addError(test, err)


def prepare_workspace() -> None:
    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    PROFILE_DIR.mkdir(parents=True)
    (CONFIG_ROOT / "basic/scenes").mkdir(parents=True)
    PLUGIN_CONFIG.mkdir(parents=True)
    PLUGIN_MANAGER_DIR.mkdir(parents=True)
    (PLUGIN_MANAGER_DIR / "modules.json").write_text(
        """[
  {
    "display_name": "mac-avcapture-legacy",
    "module_name": "mac-avcapture-legacy",
    "id": "",
    "version": "",
    "enabled": false,
    "sources": [],
    "outputs": [],
    "encoders": [],
    "services": []
  }
]
""",
        encoding="utf-8",
    )
    write_update_config("[update]", "version=0.0.0", "check_for_updates=true")
    for relative in ("Library/Caches", "Library/Logs/DiagnosticReports", "Library/Preferences"):
        (WORKDIR / relative).mkdir(parents=True)
    shutil.copy2(SOURCE_DIR / "tests/Scenarios/0010-profile-720p-basic.ini", PROFILE_DIR / "basic.ini")
    (CONFIG_ROOT / "user.ini").write_text(
        "[General]\nFirstRun=true\nLanguage=en-US\nConfirmOnExit=false\n\n"
        "[Basic]\nProfile=obs-backgroundremoval-dev-720p\nProfileDir=obs-backgroundremoval-dev-720p\n",
        encoding="utf-8",
    )
    (CONFIG_ROOT / "global.ini").write_text(
        "[General]\nMacOSPermissionsDialogLastShown=1\n", encoding="utf-8"
    )


def main() -> None:
    prepare_workspace()
    suite = unittest.defaultTestLoader.loadTestsFromTestCase(MacOSAboutDialogOnStartupTest)
    with (ARTIFACTS / "unittest.txt").open("w", encoding="utf-8") as output:
        result = unittest.TextTestRunner(
            stream=output, verbosity=2, failfast=True, resultclass=ScenarioTestResult,
        ).run(suite)
    if result.wasSuccessful():
        print("Native macOS About dialog GUI scenario passed.", flush=True)
    else:
        print(f"macOS scenario artifacts: {ARTIFACTS}", flush=True)
    raise SystemExit(not result.wasSuccessful())


if __name__ == "__main__":
    try:
        main()
    finally:
        if CURRENT_PROCESS is not None:
            stop_obs(CURRENT_PROCESS)
