# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0
# Generated by OpenAI GPT-5.6 Sol at 2026-08-21.

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path -LiteralPath $_ -PathType Leaf })]
    [string] $Runner
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

Add-Type -AssemblyName UIAutomationClient
Add-Type -AssemblyName UIAutomationTypes

$AutomationElement = [System.Windows.Automation.AutomationElement]
$TreeScope = [System.Windows.Automation.TreeScope]
$Condition = [System.Windows.Automation.Condition]
$ControlType = [System.Windows.Automation.ControlType]

function Wait-Until {
    param(
        [Parameter(Mandatory)][scriptblock] $ConditionScript,
        [Parameter(Mandatory)][string] $Description,
        [int] $TimeoutSeconds = 20
    )

    $deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    do {
        try {
            $result = & $ConditionScript
            if ($result) { return $result }
        } catch [System.Windows.Automation.ElementNotAvailableException] {
            # The Qt accessibility tree may be rebuilt while a dialog opens.
        }
        Start-Sleep -Milliseconds 100
    } while ([DateTime]::UtcNow -lt $deadline)
    throw "Timed out waiting for $Description."
}

function Find-Window {
    param([Parameter(Mandatory)][int] $ProcessId, [Parameter(Mandatory)][string] $Title)

    $processCondition = [System.Windows.Automation.PropertyCondition]::new(
        $AutomationElement::ProcessIdProperty, $ProcessId)
    $titleCondition = [System.Windows.Automation.PropertyCondition]::new(
        $AutomationElement::NameProperty, $Title)
    $windowCondition = [System.Windows.Automation.PropertyCondition]::new(
        $AutomationElement::ControlTypeProperty, $ControlType::Window)
    $combined = [System.Windows.Automation.AndCondition]::new(
        [System.Windows.Automation.Condition[]]@($processCondition, $titleCondition, $windowCondition))
    return $AutomationElement::RootElement.FindFirst($TreeScope::Descendants, $combined)
}

function Find-NamedControl {
    param(
        [Parameter(Mandatory)][System.Windows.Automation.AutomationElement] $Root,
        [Parameter(Mandatory)][string] $Name,
        [Parameter(Mandatory)][System.Windows.Automation.ControlType] $Type
    )

    $nameCondition = [System.Windows.Automation.PropertyCondition]::new(
        $AutomationElement::NameProperty, $Name)
    $typeCondition = [System.Windows.Automation.PropertyCondition]::new(
        $AutomationElement::ControlTypeProperty, $Type)
    $combined = [System.Windows.Automation.AndCondition]::new(
        [System.Windows.Automation.Condition[]]@($nameCondition, $typeCondition))
    return $Root.FindFirst($TreeScope::Descendants, $combined)
}

function Invoke-Control {
    param([Parameter(Mandatory)][System.Windows.Automation.AutomationElement] $Element)

    $pattern = $Element.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern)
    ([System.Windows.Automation.InvokePattern] $pattern).Invoke()
}

function Get-WindowText {
    param([Parameter(Mandatory)][System.Windows.Automation.AutomationElement] $Window)

    $elements = $Window.FindAll($TreeScope::Descendants, $Condition::TrueCondition)
    $parts = foreach ($element in $elements) {
        $name = $element.Current.Name
        if ($name) { $name }
        $textPattern = $null
        if ($element.TryGetCurrentPattern(
                [System.Windows.Automation.TextPattern]::Pattern,
                [ref] $textPattern)) {
            ([System.Windows.Automation.TextPattern] $textPattern).DocumentRange.GetText(-1)
        }
    }
    return $parts -join "`n"
}

$process = Start-Process -FilePath (Resolve-Path -LiteralPath $Runner).Path -PassThru
try {
    $about = Wait-Until -Description 'About obs-backgroundremoval dialog' -ConditionScript {
        Find-Window -ProcessId $process.Id -Title 'About obs-backgroundremoval'
    }

    $text = Get-WindowText -Window $about
    foreach ($expected in @(
            'Portrait Background Removal / Virtual Green-screen and Low-Light Enhancement',
            'Version 0.0.0',
            'Copyright © 2021–2026 Roy Shilkrot')) {
        if (-not $text.Contains($expected)) {
            throw "About dialog does not expose expected text: $expected"
        }
    }

    $checkboxes = $about.FindAll(
        $TreeScope::Descendants,
        [System.Windows.Automation.PropertyCondition]::new(
            $AutomationElement::ControlTypeProperty, $ControlType::CheckBox))
    if ($checkboxes.Count -ne 1) {
        throw "Expected one update-notification checkbox; found $($checkboxes.Count)."
    }
    $checkbox = $checkboxes.Item(0)
    $toggle = [System.Windows.Automation.TogglePattern] $checkbox.GetCurrentPattern(
        [System.Windows.Automation.TogglePattern]::Pattern)
    if ($toggle.Current.ToggleState -ne [System.Windows.Automation.ToggleState]::On) {
        throw 'Update-notification checkbox should initially be checked.'
    }
    $toggle.Toggle()
    Wait-Until -Description 'update-notification checkbox to clear' -ConditionScript {
        $toggle.Current.ToggleState -eq [System.Windows.Automation.ToggleState]::Off
    } | Out-Null

    $licenses = Find-NamedControl -Root $about -Name 'Licenses' -Type $ControlType::Button
    if (-not $licenses) {
        throw 'About dialog does not expose the Licenses action.'
    }
    Invoke-Control $licenses
    $licensesWindow = Wait-Until -Description 'Licenses dialog' -ConditionScript {
        Find-Window -ProcessId $process.Id -Title 'Licenses'
    }
    if (-not (Get-WindowText -Window $licensesWindow).Contains('GNU General Public License')) {
        throw 'Licenses dialog does not expose the expected license text.'
    }
    Invoke-Control (Find-NamedControl -Root $licensesWindow -Name 'Close' -Type $ControlType::Button)
    Wait-Until -Description 'Licenses dialog to close' -ConditionScript {
        -not (Find-Window -ProcessId $process.Id -Title 'Licenses')
    } | Out-Null

    Invoke-Control (Find-NamedControl -Root $about -Name 'About Qt' -Type $ControlType::Button)
    $qtWindow = Wait-Until -Description 'About Qt dialog' -ConditionScript {
        Find-Window -ProcessId $process.Id -Title 'About Qt'
    }
    if (-not (Get-WindowText -Window $qtWindow).Contains('Qt')) {
        throw 'About Qt dialog does not expose Qt information.'
    }
    Invoke-Control (Find-NamedControl -Root $qtWindow -Name 'OK' -Type $ControlType::Button)
    Wait-Until -Description 'About Qt dialog to close' -ConditionScript {
        -not (Find-Window -ProcessId $process.Id -Title 'About Qt')
    } | Out-Null

    Invoke-Control (Find-NamedControl -Root $about -Name 'OK' -Type $ControlType::Button)
    if (-not $process.WaitForExit(10000)) {
        throw 'AboutDialogRunner did not exit after accepting the dialog.'
    }
    if ($process.ExitCode -ne 0) {
        throw "AboutDialogRunner exited with code $($process.ExitCode)."
    }
    Write-Host 'PASS: Windows About dialog acceptance test'
} finally {
    if (-not $process.HasExited) {
        Stop-Process -Id $process.Id -Force
    }
}
