# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0
# Generated by OpenAI GPT-5.6 Sol at 2026-08-21.

Feature: About dialog on startup
  As an OBS user
  I want to see the plugin's About dialog once for each newly installed version
  So that I can review the product information and choose whether to receive update notifications

  Background:
    Given OBS Studio uses the "en-US" locale
    And the current build of obs-backgroundremoval is loaded

  Scenario: ST-2000.1 Show the About dialog for an unacknowledged version
    Given the current plugin version has not been acknowledged
    And update notifications are enabled
    When OBS finishes loading
    Then the "About obs-backgroundremoval" dialog is displayed
    And it shows "Portrait Background Removal / Virtual Green-screen and Low-Light Enhancement"
    And the displayed version equals the installed plugin version
    And it shows text containing "Copyright © 2021–2026 Roy Shilkrot"
    And the update-notification checkbox is checked
    And the "Licenses", "About Qt", and "OK" actions are available

  Scenario: ST-2000.2 Review licenses
    Given the About dialog is displayed
    When the user selects "Licenses"
    Then the "Licenses" dialog is displayed
    And it contains "GNU General Public License"
    When the user closes the Licenses dialog
    Then the Licenses dialog is no longer displayed

  Scenario: ST-2000.3 Review Qt information
    Given the About dialog is displayed
    When the user selects "About Qt"
    Then Qt information headed "About Qt" is displayed
    And it contains Qt information
    When the user closes the Qt information
    Then the Qt information is no longer displayed

  Scenario: ST-2000.4 Disable update notifications
    Given the About dialog is displayed
    And update notifications are enabled
    When the user clears the update-notification checkbox
    And accepts the About dialog
    Then the About dialog is no longer displayed
    And update notifications are disabled
    And the current plugin version is acknowledged

  Scenario: ST-2000.5 Do not repeat the About dialog for an acknowledged version
    Given the current plugin version has been acknowledged
    When OBS finishes loading
    Then the About dialog is not displayed

  Scenario: ST-2000.6 Preserve the notification preference for a new version
    Given an earlier plugin version has been acknowledged
    And update notifications are disabled
    When OBS finishes loading with a newer plugin version
    Then the About dialog is displayed
    And the update-notification checkbox is clear
    When the user accepts the About dialog
    Then the current plugin version is acknowledged

  Scenario: ST-2000.7 Continue when the notification preference cannot be saved
    Given the About dialog is displayed for an unacknowledged version
    And update notifications are disabled
    And the update state becomes unavailable for writing
    When the user accepts the About dialog
    Then the About dialog is no longer displayed
    And OBS continues running
    And the persisted update state is unchanged
    And OBS records "[obs-backgroundremoval] Failed to save update config"

  Scenario: ST-2000.8 Continue when update state cannot be opened
    Given the update state cannot be opened or created
    When OBS finishes loading twice under the same condition
    Then OBS continues running
    And the About dialog is never displayed
    And no update state is created
    And OBS records "[obs-backgroundremoval] Failed to open update config"

  Scenario: ST-2000.9 Continue when the current version cannot be recorded
    Given an earlier plugin version is recorded in the update state
    And the update state can be read but not written
    When OBS finishes loading twice with a newer plugin version
    Then OBS continues running
    And the About dialog is never displayed
    And the earlier plugin version remains recorded
    And OBS records "[obs-backgroundremoval] Failed to save update config"

  Scenario: ST-2000.10 Do not display while a stale temporary file is not writable
    Given an earlier plugin version is recorded in the update state
    And "update.ini.tmp" cannot be written
    When OBS finishes loading twice with a newer plugin version
    Then the About dialog is never displayed
    And the earlier plugin version remains recorded
    And OBS records "[obs-backgroundremoval] Failed to save update config"

  Scenario: ST-2000.11 Do not display while a stale temporary directory blocks saving
    Given an earlier plugin version is recorded in the update state
    And "update.ini.tmp" is a directory
    When OBS finishes loading twice with a newer plugin version
    Then the About dialog is never displayed
    And the earlier plugin version remains recorded
    And OBS records "[obs-backgroundremoval] Failed to save update config"

  Scenario: ST-2000.12 Display once after update-state storage recovers
    Given saving the current plugin version previously failed
    When update-state storage becomes writable
    Then the About dialog is displayed once
    And the current plugin version is acknowledged
    When OBS is restarted
    Then the About dialog is not displayed

  Scenario: ST-2000.13 Repair an empty update state without repeating the dialog
    Given the update state is empty
    When OBS finishes loading
    Then the About dialog is displayed once
    And the current plugin version is acknowledged
    When OBS is restarted
    Then the About dialog is not displayed

  Scenario: ST-2000.14 Repair an update state with no update section
    Given the update state contains no "update" section
    When OBS finishes loading
    Then the About dialog is displayed once
    And the current plugin version is acknowledged
    When OBS is restarted
    Then the About dialog is not displayed

  Scenario: ST-2000.15 Repair an update state with no recorded version
    Given the "update" section contains no version
    When OBS finishes loading
    Then the About dialog is displayed once
    And the current plugin version is acknowledged
    When OBS is restarted
    Then the About dialog is not displayed

  Scenario: ST-2000.16 Repair a truncated update state
    Given the update state ends in a truncated section header
    When OBS finishes loading
    Then the About dialog is displayed once
    And the current plugin version is acknowledged
    When OBS is restarted
    Then the About dialog is not displayed

  Scenario: ST-2000.17 Repair an update state containing invalid bytes
    Given the update state contains invalid UTF-8 bytes
    When OBS finishes loading
    Then the About dialog is displayed once
    And the current plugin version is acknowledged
    When OBS is restarted
    Then the About dialog is not displayed

  Scenario: ST-2000.18 Do not repeat after dismissing the dialog without OK
    Given an earlier plugin version has been acknowledged
    When OBS displays the About dialog for a newer plugin version
    And the user closes the dialog without selecting "OK"
    And OBS is restarted
    Then the About dialog is not displayed

  Scenario: ST-2000.19 Do not repeat after OBS exits while the dialog is displayed
    Given an earlier plugin version has been acknowledged
    When OBS displays the About dialog for a newer plugin version
    And OBS exits before the user dismisses the dialog
    And OBS is restarted
    Then the About dialog is not displayed

  Scenario: ST-2000.20 Display once after a downgrade
    Given a newer plugin version has already been acknowledged
    When OBS finishes loading with an older plugin version
    Then the About dialog is displayed once
    And the installed older plugin version is acknowledged
    When OBS is restarted
    Then the About dialog is not displayed
