# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

osx_deployment_target=13.0
windows_sdk_version=10.0.26100.0

# obs-deps
prebuilt_windows_x64_sha256=6f90e9598fa10cff5ad23cdcfae49b87868c07bf896b02cd464582b4ce2f2ba9
prebuilt_windows_x64_url=https://github.com/obsproject/obs-deps/releases/download/2026-07-15/windows-deps-2026-07-15-x64.zip
qt6_macos_sha256=d4b8058612a7067e44b2205fe7925ee24e9ec6b15ac8c29d3e6230c70030b102
qt6_macos_url=https://github.com/obsproject/obs-deps/releases/download/2026-07-15/macos-deps-qt6-2026-07-15-universal.tar.xz
qt6_windows_x64_sha256=7c7f985711d80467bdc1795b6592275a27d5b0e5a2c7a61db1f2c1d08d6a5579
qt6_windows_x64_url=https://github.com/obsproject/obs-deps/releases/download/2026-07-15/windows-deps-qt6-2026-07-15-x64.zip
