# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

PLUGIN_DISPLAY_NAME=OBS Background Removal
PLUGIN_AUTHOR=Roy Shilkrot
PLUGIN_EMAIL=roy.shil@gmail.com
PLUGIN_BUNDLE_ID=com.royshilkrot.obs-backgroundremoval

onnxruntime_reduced_ops_config=src/required_operators.config
osx_deployment_target=13.0
windows_sdk_version=10.0.26100

obs_studio_git_tag=32.2.1
onnxruntime_git_tag=v1.28.0
vcpkg_git_tag=2025.08.27

# obs-deps
prebuilt_macos_sha256=4ecb4c598dfa853168df6c2a0c4e0ffec8495a81fbd1ba051ef88ecd5e0f7e53
prebuilt_macos_url=https://github.com/obsproject/obs-deps/releases/download/2026-07-15/macos-deps-2026-07-15-universal.tar.xz
prebuilt_windows_x64_sha256=6f90e9598fa10cff5ad23cdcfae49b87868c07bf896b02cd464582b4ce2f2ba9
prebuilt_windows_x64_url=https://github.com/obsproject/obs-deps/releases/download/2026-07-15/windows-deps-2026-07-15-x64.zip
qt6_macos_sha256=d4b8058612a7067e44b2205fe7925ee24e9ec6b15ac8c29d3e6230c70030b102
qt6_macos_url=https://github.com/obsproject/obs-deps/releases/download/2026-07-15/macos-deps-qt6-2026-07-15-universal.tar.xz
qt6_windows_x64_sha256=7c7f985711d80467bdc1795b6592275a27d5b0e5a2c7a61db1f2c1d08d6a5579
qt6_windows_x64_url=https://github.com/obsproject/obs-deps/releases/download/2026-07-15/windows-deps-qt6-2026-07-15-x64.zip

# tools
ccache_macos_sha256=0274210ec9c9936ed5711d59b0de3167a51216a588ddde35f6bc828f366fe6d9
ccache_macos_url=https://github.com/ccache/ccache/releases/download/v4.13.6/ccache-4.13.6-darwin.tar.gz
ccache_macos_version=4.13.6
ccache_windows_sha256=3d7cebb05850ad704e197b3f1d3f0f924ab6c9fdfc561578e146184fe9d89380
ccache_windows_url=https://github.com/ccache/ccache/releases/download/v4.13.6/ccache-4.13.6-windows-x86_64.zip
ccache_windows_version=4.13.6
