version = 1

[[annotations]]
path = "NOTICE"
SPDX-FileCopyrightText = ""
SPDX-License-Identifier = "LicenseRef-Not-Copyrightable"

[[annotations]]
path = [
  ".python-version",
  "CMakePresets.json",
  "compile_flags.txt",
  "scripts/windows/*",
  "vcpkg-configuration.json",
  "vcpkg.json",
  "VERSION",
]
SPDX-FileCopyrightText = "2026 Kaito Udagawa <umireon@kaito.tokyo>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["data/locale/*.ini"]
SPDX-FileCopyrightText = ""
SPDX-License-Identifier = "CC0-1.0"
