# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Build Plugin macOS

on:
  workflow_call:
    inputs:
      runs-on:
        description: GitHub Actions runner label.
        required: true
        type: string
      DEVELOPER_DIR:
        description: Xcode developer directory.
        required: true
        type: string
      osx-deploy-target:
        description: Minimum macOS deployment target.
        required: true
        type: string
      upload-artifacts:
        description: Flag to upload artifacts.
        required: true
        type: boolean
      x86_64:
        description: Flag to build for x86_64.
        required: false
        type: boolean
        default: false


env:
  HOMEBREW_NO_ANALYTICS: '1'
  HOMEBREW_NO_AUTO_UPDATE: '1'
  HOMEBREW_NO_ENV_HINTS: '1'
  HOMEBREW_NO_INSTALL_CLEANUP: '1'
  VCPKG_BINARY_SOURCES: clear;http,https://vcpkg-obs.kaito.tokyo/{sha},read

jobs:
  build-plugin-macos:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 180

    env:
      UNSIGNED_PLUGIN_ARTIFACT_NAME: obs-backgroundremoval-macos-${{ inputs.x86_64 && 'x86_64' || 'arm64' }}.unsigned-plugin.tar.zst
      CMAKE_OSX_ARCHITECTURES: ${{ inputs.x86_64 && 'x86_64' || 'arm64' }}
      CMAKE_OSX_DEPLOYMENT_TARGET: ${{ inputs.osx-deploy-target }}
      DEVELOPER_DIR: ${{ inputs.DEVELOPER_DIR }}
      VCPKG_BINARY_SOURCES: clear;http,https://vcpkg-obs.kaito.tokyo/{sha},read
      VCPKG_ORT_TARGET_TRIPLET: ${{ inputs.x86_64 && 'x64-osx-obs-ort' || 'arm64-osx-obs-ort' }}
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_TARGET_TRIPLET: ${{ inputs.x86_64 && 'x64-osx-obs' || 'arm64-osx-obs' }}

    steps:
      - name: Print runner info (macos)
        id: runner-macos
        shell: pwsh -command "Set-StrictMode -Version Latest; $ErrorActionPreference = 'Stop'; $PSNativeCommandUseErrorActionPreference = $true; . '{0}'"
        run: |
          Add-Content -LiteralPath $env:GITHUB_OUTPUT -Value "ImageVersion=$env:ImageVersion" -Encoding utf8
          Add-Content -LiteralPath $env:GITHUB_OUTPUT -Value "macos_product_version=$(sw_vers -productVersion)" -Encoding utf8

      - name: Print Xcode info
        id: xcode
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          printf 'version=%s\n' "$(xcodebuild -version | awk 'NR == 1 { print $2 }')" | tee -a "${GITHUB_OUTPUT:?}"
          printf 'build_version=%s\n' "$(xcodebuild -version | awk 'NR == 2 { print $3 }')" | tee -a "${GITHUB_OUTPUT:?}"

      - name: Install pkgconf (macOS)
        id: pkgconf
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          brew install pkgconf
          printf 'bindir=%s\n' "$(brew --prefix pkgconf)/bin" >>"${GITHUB_OUTPUT:?}"

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Load buildspec.props
        id: buildspec
        shell: pwsh
        run: |
          foreach ($entry in (Get-Content -LiteralPath buildspec.props -Raw | ConvertFrom-StringData).GetEnumerator()) {
            Add-Content -LiteralPath $env:GITHUB_OUTPUT -Value "$($entry.Key)=$($entry.Value)" -Encoding utf8
          }

      # BEGIN: Checkout dependencies

      - name: Checkout vcpkg
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: microsoft/vcpkg
          ref: ${{ steps.buildspec.outputs.vcpkg_git_tag }}
          path: vcpkg
          filter: blob:none
          persist-credentials: false

      - name: Assert vcpkg git commit
        uses: ./.github/actions/assert-git-checkout
        with:
          path: vcpkg
          git-commit: ${{ steps.buildspec.outputs.vcpkg_git_commit }}

      - name: Checkout OBS Studio
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: obsproject/obs-studio
          ref: ${{ steps.buildspec.outputs.obs_studio_git_tag }}
          path: obs-studio
          filter: blob:none
          submodules: recursive
          persist-credentials: false

      - name: Assert OBS Studio git commit
        uses: ./.github/actions/assert-git-checkout
        with:
          path: obs-studio
          git-commit: ${{ steps.buildspec.outputs.obs_studio_git_commit }}

      - name: Checkout ONNX Runtime
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: microsoft/onnxruntime
          ref: ${{ steps.buildspec.outputs.onnxruntime_git_tag }}
          path: onnxruntime
          filter: blob:none
          submodules: recursive
          persist-credentials: false

      - name: Assert ONNX Runtime git commit
        uses: ./.github/actions/assert-git-checkout
        with:
          path: onnxruntime
          git-commit: ${{ steps.buildspec.outputs.onnxruntime_git_commit }}

      # END: Checkout dependencies

      - name: Initialize JOB_TEMP (macOS)
        id: job-temp
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          JOB_TEMP="$(mktemp -d -t "${GITHUB_JOB:?}-${GITHUB_RUN_ID:?}.XXXXXXX")"
          printf 'JOB_TEMP=%s\n' "${JOB_TEMP:?}" >>"${GITHUB_OUTPUT:?}"

      # BEGIN: Set up toolchains

      - name: Run bootstrap-vcpkg.sh
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          PKGCONF_BINDIR: ${{ steps.pkgconf.outputs.bindir }}
        run: |
          env -i \
            DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
            HOME="${HOME:?}" \
            PATH="${PKGCONF_BINDIR:?}:/usr/bin:/bin" \
            VCPKG_ROOT="${VCPKG_ROOT:?}" \
            "${VCPKG_ROOT:?}/bootstrap-vcpkg.sh" -disableMetrics

      - name: Fetch vcpkg tools (macOS)
        id: vcpkg-tools
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          vcpkg_fetch() {
            env -i \
              DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
              HOME="${HOME:?}" \
              PATH='/usr/bin:/bin' \
              VCPKG_ROOT="${VCPKG_ROOT:?}" \
              "${VCPKG_ROOT:?}/vcpkg" fetch "${1:?}" | tail -n1
          }

          printf 'CMAKE_COMMAND=%s\n' "$(vcpkg_fetch cmake)" | tee -a "${GITHUB_OUTPUT:?}"
          printf 'NINJA_COMMAND=%s\n' "$(vcpkg_fetch ninja)" | tee -a "${GITHUB_OUTPUT:?}"

      - name: Set up ccache (macOS)
        id: setup-ccache
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          JOB_TEMP: ${{ steps.job-temp.outputs.JOB_TEMP }}
          VERSION: ${{ steps.buildspec.outputs.ccache_macos_version }}
          URL: ${{ steps.buildspec.outputs.ccache_macos_url }}
          SHA256: ${{ steps.buildspec.outputs.ccache_macos_sha256 }}
        run: |
          curl -fsSLo "${JOB_TEMP:?}/${URL##*/}" "${URL:?}"
          printf '%s  %s\n' "${SHA256:?}" "${JOB_TEMP:?}/${URL##*/}" | shasum -a 256 -c -
          mkdir -p "${GITHUB_WORKSPACE:?}/.bin"
          tar --strip-components 1 -C "${GITHUB_WORKSPACE:?}/.bin" -xf "${JOB_TEMP:?}/${URL##*/}" '*/ccache'
          chmod 755 "${GITHUB_WORKSPACE:?}/.bin/ccache"
          printf 'path=%s\n' "${GITHUB_WORKSPACE:?}/.bin/ccache" | tee -a "${GITHUB_OUTPUT:?}"
          printf 'version=%s\n' "${VERSION:?}" | tee -a "${GITHUB_OUTPUT:?}"

      - name: Set up obs-deps (macOS)
        id: setup-obs-deps
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          JOB_TEMP: ${{ steps.job-temp.outputs.JOB_TEMP }}
          NAME: ${{ steps.buildspec.outputs.prebuilt_macos_name }}
          URL: ${{ steps.buildspec.outputs.prebuilt_macos_url }}
          SHA256: ${{ steps.buildspec.outputs.prebuilt_macos_sha256 }}
        run: |
          curl -fsSLo "${JOB_TEMP:?}/${URL##*/}" "${URL:?}"
          printf '%s  %s\n' "${SHA256:?}" "${JOB_TEMP:?}/${URL##*/}" | shasum -a 256 -c -
          mkdir -p "${GITHUB_WORKSPACE:?}/${NAME:?}"
          tar -C "${GITHUB_WORKSPACE:?}/${NAME:?}" -xf "${JOB_TEMP:?}/${URL##*/}"
          printf 'prefix=%s\n' "${GITHUB_WORKSPACE:?}/${NAME:?}" | tee -a "${GITHUB_OUTPUT:?}"

      - name: Set up obs-deps-qt6 (macOS)
        id: setup-obs-deps-qt6
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          JOB_TEMP: ${{ steps.job-temp.outputs.JOB_TEMP }}
          NAME: ${{ steps.buildspec.outputs.qt6_macos_name }}
          URL: ${{ steps.buildspec.outputs.qt6_macos_url }}
          SHA256: ${{ steps.buildspec.outputs.qt6_macos_sha256 }}
        run: |
          curl -fsSLo "${JOB_TEMP:?}/${URL##*/}" "${URL:?}"
          printf '%s  %s\n' "${SHA256:?}" "${JOB_TEMP:?}/${URL##*/}" | shasum -a 256 -c -
          mkdir -p "${GITHUB_WORKSPACE:?}/${NAME:?}"
          tar -C "${GITHUB_WORKSPACE:?}/${NAME:?}" -xf "${JOB_TEMP:?}/${URL##*/}"
          printf 'prefix=%s\n' "${GITHUB_WORKSPACE:?}/${NAME:?}" | tee -a "${GITHUB_OUTPUT:?}"

      # END: Set up toolchains

      - name: Configure obs-studio (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CMAKE_COMMAND: ${{ steps.vcpkg-tools.outputs.CMAKE_COMMAND }}
          CMAKE_PREFIX_PATH: ${{ steps.setup-obs-deps.outputs.prefix }};${{ steps.setup-obs-deps-qt6.outputs.prefix }}
          OBS_VERSION_OVERRIDE: ${{ steps.buildspec.outputs.obs_studio_git_tag }}
        run: |
          env -i \
            DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
            HOME="${HOME:?}" \
            PATH="${CMAKE_COMMAND%/*}:/usr/bin:/bin" \
            cmake \
            -S "${GITHUB_WORKSPACE:?}/obs-studio" \
            -B "${GITHUB_WORKSPACE:?}/build_obs" \
            -G Xcode \
            -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE:?}/obs_installed" \
            -DCMAKE_OSX_ARCHITECTURES="${CMAKE_OSX_ARCHITECTURES:?}" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET="${CMAKE_OSX_DEPLOYMENT_TARGET:?}" \
            -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH:?}" \
            -DENABLE_FRONTEND=OFF \
            -DENABLE_PLUGINS=OFF \
            -DOBS_CMAKE_VERSION=3.0.0 \
            -DOBS_VERSION_OVERRIDE="${OBS_VERSION_OVERRIDE:?}"

      - name: Build obs-studio (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CMAKE_COMMAND: ${{ steps.vcpkg-tools.outputs.CMAKE_COMMAND }}
        run: |
          env -i \
            DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
            HOME="${HOME:?}" \
            PATH="${CMAKE_COMMAND%/*}:/usr/bin:/bin" \
            cmake --build build_obs --target obs-frontend-api --config Release --parallel

      - name: Install obs-studio (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: cmake --install build_obs --component Development --config Release --prefix obs_installed

      - name: Install vcpkg dependencies (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          PKGCONF_BINDIR: ${{ steps.pkgconf.outputs.bindir }}
        run: |
          env -i \
            DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
            HOME="${HOME:?}" \
            PATH="${PKGCONF_BINDIR:?}:/usr/bin:/bin" \
            VCPKG_BINARY_SOURCES="${VCPKG_BINARY_SOURCES:?}" \
            VCPKG_ROOT="${VCPKG_ROOT:?}" \
            "${VCPKG_ROOT:?}/vcpkg" install \
            --triplet="${VCPKG_TARGET_TRIPLET:?}"

      - name: Install vcpkg_ort dependencies (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          PKGCONF_BINDIR: ${{ steps.pkgconf.outputs.bindir }}
        run: |
          env -i \
            DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
            HOME="${HOME:?}" \
            PATH="${PKGCONF_BINDIR:?}:/usr/bin:/bin" \
            VCPKG_BINARY_SOURCES="${VCPKG_BINARY_SOURCES:?}" \
            VCPKG_ROOT="${VCPKG_ROOT:?}" \
            "${VCPKG_ROOT:?}/vcpkg" install \
            --triplet="${VCPKG_ORT_TARGET_TRIPLET:?}" \
            --overlay-triplets="${GITHUB_WORKSPACE:?}/vcpkg-triplets" \
            --x-feature=coreml-ep \
            --x-install-root="${GITHUB_WORKSPACE:?}/vcpkg_ort_installed" \
            --x-manifest-root="${GITHUB_WORKSPACE:?}/onnxruntime/cmake"

      - name: Restore ccache_ort (macOS)
        id: ccache_ort
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ github.workspace }}/.ccache_ort
          key: ccache_ort-v1--${{ runner.os }}-${{ inputs.x86_64 && 'x86_64' || 'arm64' }}-${{ steps.runner-macos.outputs.macos_product_version }}-${{ steps.xcode.outputs.version }}-${{ steps.xcode.outputs.build_version }}-${{ steps.setup-ccache.outputs.version }}-${{ inputs.osx-deploy-target }}--${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ccache_ort-v1--${{ runner.os }}-${{ inputs.x86_64 && 'x86_64' || 'arm64' }}-${{ steps.runner-macos.outputs.macos_product_version }}-${{ steps.xcode.outputs.version }}-${{ steps.xcode.outputs.build_version }}-${{ steps.setup-ccache.outputs.version }}-${{ inputs.osx-deploy-target }}--${{ github.run_id }}-
            ccache_ort-v1--${{ runner.os }}-${{ inputs.x86_64 && 'x86_64' || 'arm64' }}-${{ steps.runner-macos.outputs.macos_product_version }}-${{ steps.xcode.outputs.version }}-${{ steps.xcode.outputs.build_version }}-${{ steps.setup-ccache.outputs.version }}-${{ inputs.osx-deploy-target }}--

      - name: Reset ccache_ort stats
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CCACHE_COMMAND: ${{ steps.setup-ccache.outputs.path }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache_ort
        run: '"${CCACHE_COMMAND:?}" --zero-stats'

      - name: Install build-time Python dependencies
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: /usr/bin/python3 -m pip install --user -r requirements-build.txt

      - name: Generate reduced operators for onnxruntime
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          REDUCED_OPS_CONFIG_PATH: ${{ steps.buildspec.outputs.onnxruntime_reduced_ops_config }}
        run: |
          /usr/bin/python3 onnxruntime/tools/ci_build/reduce_op_kernels.py \
            "${REDUCED_OPS_CONFIG_PATH:?}" \
            --cmake_build_dir build_ort \
            --is_extended_minimal_build_or_higher

      - name: Configure onnxruntime (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CCACHE_COMMAND: ${{ steps.setup-ccache.outputs.path }}
          CMAKE_COMMAND: ${{ steps.vcpkg-tools.outputs.CMAKE_COMMAND }}
          NINJA_COMMAND: ${{ steps.vcpkg-tools.outputs.NINJA_COMMAND }}
          PKGCONF_BINDIR: ${{ steps.pkgconf.outputs.bindir }}
        run: |
          env -i \
            CCACHE_BASEDIR="${GITHUB_WORKSPACE:?}" \
            CCACHE_DIR="${GITHUB_WORKSPACE:?}/.ccache_ort" \
            CCACHE_SLOPPINESS='include_file_mtime,time_macros' \
            DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
            HOME="${HOME:?}" \
            PATH="${PKGCONF_BINDIR:?}:${CMAKE_COMMAND%/*}:${NINJA_COMMAND%/*}:/usr/bin:/bin" \
            cmake -S onnxruntime/cmake -B build_ort -G Ninja \
            --compile-no-warning-as-error \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER_LAUNCHER=${CCACHE_COMMAND:?} \
            -DCMAKE_CXX_COMPILER_LAUNCHER=${CCACHE_COMMAND:?} \
            -DCMAKE_OSX_ARCHITECTURES="${CMAKE_OSX_ARCHITECTURES:?}" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET="${CMAKE_OSX_DEPLOYMENT_TARGET:?}" \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
            -DCMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT:?}/scripts/buildsystems/vcpkg.cmake" \
            -DPython_EXECUTABLE="/usr/bin/python3" \
            -DVCPKG_INSTALLED_DIR="${GITHUB_WORKSPACE:?}/vcpkg_ort_installed" \
            -DVCPKG_MANIFEST_INSTALL=OFF \
            -DVCPKG_OVERLAY_TRIPLETS="${GITHUB_WORKSPACE:?}/vcpkg-triplets" \
            -DVCPKG_TARGET_TRIPLET="${VCPKG_ORT_TARGET_TRIPLET:?}" \
            -Donnxruntime_BUILD_SHARED_LIB=OFF \
            -Donnxruntime_BUILD_UNIT_TESTS=OFF \
            -Donnxruntime_DISABLE_RTTI=OFF \
            -Donnxruntime_REDUCED_OPS_BUILD=ON \
            -Donnxruntime_RUN_ONNX_TESTS=OFF \
            -Donnxruntime_USE_COREML=ON \
            -Donnxruntime_USE_VCPKG=ON

      - name: Build onnxruntime (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CMAKE_COMMAND: ${{ steps.vcpkg-tools.outputs.CMAKE_COMMAND }}
          NINJA_COMMAND: ${{ steps.vcpkg-tools.outputs.NINJA_COMMAND }}
        run: |
          env -i \
            CCACHE_BASEDIR="${GITHUB_WORKSPACE:?}" \
            CCACHE_DIR="${GITHUB_WORKSPACE:?}/.ccache_ort" \
            CCACHE_SLOPPINESS='include_file_mtime,time_macros' \
            DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
            HOME="${HOME:?}" \
            PATH="${CMAKE_COMMAND%/*}:${NINJA_COMMAND%/*}:/usr/bin:/bin" \
            cmake --build build_ort --config Release --parallel

      - name: Install onnxruntime (macOS)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: cmake --install build_ort --prefix ort_installed

      - name: Save ccache_ort
        if: success() && steps.ccache_ort.outputs.cache-hit != 'true'
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ github.workspace }}/.ccache_ort
          key: ${{ steps.ccache_ort.outputs.cache-primary-key }}

      - name: Show ccache_ort stats
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CCACHE_COMMAND: ${{ steps.setup-ccache.outputs.path }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache_ort
        run: '"${CCACHE_COMMAND}" --show-stats | tee -a "${GITHUB_STEP_SUMMARY:?}"'

      - name: Configure
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CMAKE_COMMAND: ${{ steps.vcpkg-tools.outputs.CMAKE_COMMAND }}
          NINJA_COMMAND: ${{ steps.vcpkg-tools.outputs.NINJA_COMMAND }}
          CMAKE_PREFIX_PATH: ${{ steps.setup-obs-deps.outputs.prefix }};${{ steps.setup-obs-deps-qt6.outputs.prefix }};${{ github.workspace }}/obs_installed;${{ github.workspace }}/obs_installed/Frameworks;${{ github.workspace }}/vcpkg_ort_installed/${{ env.VCPKG_ORT_TARGET_TRIPLET }};${{ github.workspace }}/ort_installed;${{ github.workspace }}/vcpkg_installed/${{ env.VCPKG_TARGET_TRIPLET }}
        run: |
          env -i \
            DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
            HOME="${HOME:?}" \
            PATH="${CMAKE_COMMAND%/*}:${NINJA_COMMAND%/*}:/usr/bin:/bin" \
            cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_OSX_ARCHITECTURES="${CMAKE_OSX_ARCHITECTURES:?}" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET="${CMAKE_OSX_DEPLOYMENT_TARGET:?}" \
            -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH:?}"

      - name: Build
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CMAKE_COMMAND: ${{ steps.vcpkg-tools.outputs.CMAKE_COMMAND }}
          NINJA_COMMAND: ${{ steps.vcpkg-tools.outputs.NINJA_COMMAND }}
        run: |
          env -i \
            DEVELOPER_DIR="${DEVELOPER_DIR:?}" \
            HOME="${HOME:?}" \
            PATH="${CMAKE_COMMAND%/*}:${NINJA_COMMAND%/*}:/usr/bin:/bin" \
            cmake --build build --config RelWithDebInfo --parallel

      - name: Install
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: cmake --install build --config RelWithDebInfo --prefix build_prefix

      - name: Compress unsigned plugin artifact
        if: inputs.upload-artifacts
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          COPYFILE_DISABLE=1 ZSTD_CLEVEL=19 tar --no-mac-metadata --no-xattrs \
            -C 'build_prefix/Library/Application Support/obs-studio/plugins' \
            -acf "${GITHUB_WORKSPACE:?}/${UNSIGNED_PLUGIN_ARTIFACT_NAME:?}" \
            obs-backgroundremoval.plugin

      - name: Attest unsigned plugin artifact
        if: inputs.upload-artifacts
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-path: ${{ env.UNSIGNED_PLUGIN_ARTIFACT_NAME }}

      - name: Upload unsigned plugin artifact
        if: inputs.upload-artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          # The `name` input will be ignored with `archive: false`.
          # Refer to https://github.com/actions/upload-artifact/blob/main/action.yml
          path: obs-backgroundremoval-macos-${{ env.CMAKE_OSX_ARCHITECTURES }}.unsigned-plugin.tar.zst
          archive: false
          if-no-files-found: error
