# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Check CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-clang-format:
    name: Check clang-format

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Print clang-format version
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          clang-format-18 --version

      - name: Check with clang-format
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          git ls-files -z "*.c" "*.cpp" "*.h" "*.hpp" | xargs -0 -r clang-format-18 --dry-run --Werror

  check-gersemi:
    name: Check gersemi

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python for check requirements
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: .python-version

      - name: Install check requirements
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          python -m pip install -r requirements-check.txt

      - name: Check with gersemi
        shell: bash
        run: |
          set -euo pipefail
          git ls-files CMakeLists.txt "*.cmake" | xargs --no-run-if-empty gersemi --check

  check-reuse:
    name: Check reuse

    runs-on: ubuntu-slim
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python for check requirements
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: .python-version

      - name: Install check requirements
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          python -m pip install -r requirements-check.txt

      - name: Lint with REUSE
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          reuse lint
