# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: CI Config

# file: .github/workflows/ci-config.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-06-22

on:
  workflow_call:
    outputs:
      WINDOWS_SDK_VERSION:
        value: ${{ fromJson(jobs.ci-config.outputs.CMAKE_PRESETS_WINDOWS).cacheVariables.CMAKE_SYSTEM_VERSION }}
      OSX_DEPLOYMENT_TARGET:
        value: ${{ fromJson(jobs.ci-config.outputs.CMAKE_PRESETS_MACOS).cacheVariables.CMAKE_OSX_DEPLOYMENT_TARGET }}
      VCPKG_BINARY_SOURCES:
        value: clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha},read

jobs:
  ci-config:
    outputs:
      CMAKE_PRESETS_WINDOWS: ${{ steps.cmakepresets-json.outputs.windows }}
      CMAKE_PRESETS_MACOS: ${{ steps.cmakepresets-json.outputs.macos }}
      CMAKE_PRESETS_LINUX: ${{ steps.cmakepresets-json.outputs.linux }}

    runs-on: ubuntu-slim
    timeout-minutes: 30

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Extract CMakePresets.json
        id: cmakepresets-json
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          for name in windows macos linux; do
            printf '%s<<EOS\n' "$name" >> "$GITHUB_OUTPUT"
            <CMakePresets.json jq --arg presetName "$name" '.configurePresets[] | select(.name == $presetName)' | tee -a "$GITHUB_OUTPUT"
            printf '\nEOS\n' >> "$GITHUB_OUTPUT"
          done
