# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: ORT CI

# file: .github/workflows/ort.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-06-22

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["*"]
  schedule:
    - cron: 17 4 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci-config:
    permissions:
      contents: read
    uses: ./.github/workflows/ci-config.yml

  build-windows:
    needs: [ci-config]
    permissions:
      contents: read
    uses: ./.github/workflows/ort-build-windows.yml
    with:
      job-index: 0
      WINDOWS_SDK_VERSION: ${{ needs.ci-config.outputs.WINDOWS_SDK_VERSION }}
      VCPKG_VERSION: ${{ needs.ci-config.outputs.VCPKG_VERSION }}
      ORT_VERSION: ${{ needs.ci-config.outputs.ORT_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ needs.ci-config.outputs.VCPKG_BINARY_SOURCES }}

  build-macos:
    needs: [ci-config]
    permissions:
      contents: read
    uses: ./.github/workflows/ort-build-macos.yml
    with:
      job-index: 0
      runs-on: macos-15
      DEVELOPER_DIR: /Applications/Xcode_16.4.app
      OSX_DEPLOYMENT_TARGET: ${{ needs.ci-config.outputs.OSX_DEPLOYMENT_TARGET }}
      VCPKG_VERSION: ${{ needs.ci-config.outputs.VCPKG_VERSION }}
      ORT_VERSION: ${{ needs.ci-config.outputs.ORT_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ needs.ci-config.outputs.VCPKG_BINARY_SOURCES }}

  # build-ubuntu:
  #   permissions:
  #     contents: read
  #   uses: ./.github/workflows/ort-build-ubuntu.yml
  #   with:
  #     VCPKG_BINARY_SOURCES: 'clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha}'
  #     ort-version: v1.24.4

  accept-ort:
    name: Accept ORT CI
    needs:
      - build-windows
      - build-macos
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Accept ort
        run: |
          echo 'The workflow ort has completed successfully.'
