# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

# FIXME: DISABLED TEMPORARILY

name: Plugin CI

# file: .github/workflows/plugin.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-05-21

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['*']

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  config:
    permissions: {}
    runs-on: ubuntu-slim
    timeout-minutes: 10
    outputs:
      ORT_VERSION: ${{ steps.config.outputs.ORT_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ steps.config.outputs.VCPKG_BINARY_SOURCES }}
      VCPKG_VERSION: ${{ steps.config.outputs.VCPKG_VERSION }}
    steps:
      - name: Output config
        id: config
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          echo 'ORT_VERSION=v1.24.4' >> "${GITHUB_OUTPUT}"
          echo 'VCPKG_BINARY_SOURCES=clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha},read' >> "${GITHUB_OUTPUT}"
          echo 'VCPKG_VERSION=2026.04.27' >> "${GITHUB_OUTPUT}"

  # build-windows:
  #   needs: config
  #   permissions:
  #     contents: read
  #   uses: ./.github/workflows/plugin-build-windows.yml
  #   with:
  #     VCPKG_BINARY_SOURCES: ${{ needs.config.outputs.VCPKG_BINARY_SOURCES }}
  #     vcpkg-version: ${{ needs.config.outputs.VCPKG_VERSION }}
  #     ort-version: ${{ needs.config.outputs.ORT_VERSION }}

  # build-macos:
  #   needs: config
  #   permissions:
  #     contents: read
  #   uses: ./.github/workflows/plugin-build-macos.yml
  #   with:
  #     VCPKG_BINARY_SOURCES: ${{ needs.config.outputs.VCPKG_BINARY_SOURCES }}
  #     vcpkg-version: ${{ needs.config.outputs.VCPKG_VERSION }}
  #     ort-version: ${{ needs.config.outputs.ORT_VERSION }}
  #     codesign-enabled: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}
  #     DEVELOPER_DIR: /Applications/Xcode_16.4.app
  #   secrets: inherit

  # build-ubuntu:
  #   needs: config
  #   permissions:
  #     contents: read
  #   uses: ./.github/workflows/plugin-build-ubuntu.yml
  #   with:
  #     VCPKG_BINARY_SOURCES: ${{ needs.config.outputs.VCPKG_BINARY_SOURCES }}
  #     vcpkg-version: ${{ needs.config.outputs.VCPKG_VERSION }}
  #     ort-version: ${{ needs.config.outputs.ORT_VERSION }}

  accept-plugin:
    name: Accept Plugin CI
    # needs: [build-windows, build-macos, build-ubuntu]
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Accept plugin
        run: |
          echo 'The workflow plugin has completed successfully.'

  # release:
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
  #   needs: accept-plugin
  #   permissions:
  #     artifact-metadata: write
  #     attestations: write
  #     contents: write
  #     id-token: write
  #   uses: ./.github/workflows/plugin-release.yml
