# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Plugin Build Debian

# file: .github/workflows/plugin-build-debian.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-06-24

on:
  workflow_call:
    inputs:
      job-index:
        description: The job index for logging.
        required: true
        type: number
      environment:
        description: The environment name for this workflow, or empty string for no environment
        required: false
        type: string
        default: ''
      runs-on:
        description: The runner label to run this workflow on.
        required: true
        type: string
      image:
        description: The image to run this workflow on.
        required: true
        type: string

permissions: {}

jobs:
  plugin-build-debian-forky:
    permissions:
      contents: read
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.environment }}
    timeout-minutes: 180
    container: ${{ inputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install dependencies
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            cmake \
            file \
            libcurl4-openssl-dev \
            libobs-dev \
            libonnxruntime-dev \
            libopencv-dev

      - name: Configure Plugin (Debian)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          . /etc/os-release
          cmake --preset linux -DPACKAGE_VERSION_SUFFIX="~$VERSION_CODENAME"

      - name: Build Plugin (Debian)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          cmake --build --preset linux

      - name: Package Plugin (Debian)
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        working-directory: build
        run: |
          cpack -G DEB

      - name: Upload Plugin Binary (Debian)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pluginbinary-debian-${{ runner.arch }}-${{ github.run_id }}
          path: |
            build/*.deb
            build/*.ddeb
          if-no-files-found: error
          retention-days: 7
