# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Plugin Build macOS

# file: .github/workflows/plugin-build-macos.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-06-23

on:
  workflow_call:
    inputs:
      job-index:
        description: The job index for logging.
        required: true
        type: number
      environment:
        description: The environment name for this workflow, or empty string for no environment
        required: false
        type: string
        default: ''
      runs-on:
        description: The runner label to run this workflow on.
        required: true
        type: string
      DEVELOPER_DIR:
        description: The value of DEVELOPER_DIR environment variable.
        required: true
        type: string
      OSX_DEPLOYMENT_TARGET:
        description: The deployment target of macOS.
        required: true
        type: string
      VCPKG_BINARY_SOURCES:
        description: VCPKG_BINARY_SOURCES environment variable for the build jobs.
        required: true
        type: string
      build-obs:
        description: Flag to build OBS Studio.
        required: false
        type: boolean
        default: true
      install-vcpkg:
        description: Flag to install vcpkg dependencies.
        required: false
        type: boolean
        default: true
      build-onnxruntime:
        description: Flag to build ONNX Runtime.
        required: false
        type: boolean
        default: true

    secrets:
      MACOS_NOTARIZATION_PASSWORD:
        required: false
      MACOS_NOTARIZATION_USERNAME:
        required: false
      MACOS_SIGNING_APPLICATION_IDENTITY:
        required: false
      MACOS_SIGNING_CERT_PASSWORD:
        required: false
      MACOS_SIGNING_CERT:
        required: false
      MACOS_SIGNING_INSTALLER_IDENTITY:
        required: false

permissions: {}

jobs:
  plugin-build-macos:
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 180

    permissions:
      contents: read

    env:
      DEVELOPER_DIR: ${{ inputs.DEVELOPER_DIR }}
      ORT_CCACHE_DIR: '${{ github.workspace }}/.ccache_ort'
      OSX_ARCHITECTURES: arm64;x86_64
      OSX_DEPLOYMENT_TARGET: ${{ inputs.OSX_DEPLOYMENT_TARGET }}
      VCPKG_BINARY_SOURCES: '${{ inputs.VCPKG_BINARY_SOURCES }}'

    steps:
      - name: Output Image Metadata
        id: image-metadata
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          echo "ImageVersion=$ImageVersion" >> "$GITHUB_OUTPUT"

      - name: Print Xcode version
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          xcodebuild -version

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Extract buildspec.props
        id: buildspec
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          awk '!/(^#|^[[:space:]]*$)/' buildspec.props >> "$GITHUB_OUTPUT"

      - name: Set up Python for build requirements
        id: setup-python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: .python-version
          pip-install: -r requirements-build.txt

      - name: Set up ccache
        id: setup-ccache
        uses: ./.github/actions/setup-ccache

      - name: Checkout vcpkg
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: microsoft/vcpkg
          ref: ${{ steps.buildspec.outputs.vcpkg_default_git_tag }}
          persist-credentials: false
          path: vcpkg
          filter: blob:none

      - name: Assert vcpkg git commit
        shell: pwsh
        working-directory: vcpkg
        env:
          GIT_COMMIT: ${{ steps.buildspec.outputs.vcpkg_default_git_commit }}
        run: |
          $actualGitCommit = git rev-parse HEAD
          if ($actualGitCommit -ne $env:GIT_COMMIT) { throw "Git commit not match: expected $env:GIT_COMMIT, actual $actualGitCommit" }

      - name: Checkout vcpkg (ONNX Runtime)
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: microsoft/vcpkg
          ref: ${{ steps.buildspec.outputs.vcpkg_ort_git_tag }}
          persist-credentials: false
          path: vcpkg_ort
          filter: blob:none

      - name: Assert vcpkg git commit (ONNX Runtime)
        shell: pwsh
        working-directory: vcpkg_ort
        env:
          GIT_COMMIT: ${{ steps.buildspec.outputs.vcpkg_ort_git_commit }}
        run: |
          $actualGitCommit = git rev-parse HEAD
          if ($actualGitCommit -ne $env:GIT_COMMIT) { throw "Git commit not match: expected $env:GIT_COMMIT, actual $actualGitCommit" }

      - name: Checkout obs-studio
        if: inputs.build-obs
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: obsproject/obs-studio
          ref: ${{ steps.buildspec.outputs.obs_studio_git_tag }}
          persist-credentials: false
          path: obs-studio
          filter: blob:none

      - name: Assert obs-studio git commit
        if: inputs.build-obs
        shell: pwsh
        working-directory: obs-studio
        env:
          GIT_COMMIT: ${{ steps.buildspec.outputs.obs_studio_git_commit }}
        run: |
          $actualGitCommit = git rev-parse HEAD
          if ($actualGitCommit -ne $env:GIT_COMMIT) { throw "Git commit not match: expected $env:GIT_COMMIT, actual $actualGitCommit" }

      - name: Checkout ONNX Runtime
        if: inputs.build-onnxruntime
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: microsoft/onnxruntime
          ref: ${{ steps.buildspec.outputs.onnxruntime_git_tag }}
          persist-credentials: false
          path: onnxruntime
          submodules: recursive

      - name: Assert onnxruntime git commit
        if: inputs.build-onnxruntime
        shell: pwsh
        working-directory: onnxruntime
        env:
          GIT_COMMIT: ${{ steps.buildspec.outputs.onnxruntime_git_commit }}
        run: |
          $actualGitCommit = git rev-parse HEAD
          if ($actualGitCommit -ne $env:GIT_COMMIT) { throw "Git commit not match: expected $env:GIT_COMMIT, actual $actualGitCommit" }

      - name: Run bootstrap-vcpkg.sh
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: Run bootstrap-vcpkg.sh (ONNX Runtime)
        if: inputs.build-onnxruntime
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          ./vcpkg_ort/bootstrap-vcpkg.sh -disableMetrics

      - name: Build OBS (macOS)
        if: inputs.build-obs
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          Set-StrictMode -Version Latest; $ErrorActionPreference = 'Stop'; $PSNativeCommandUseErrorActionPreference = $true

          Import-Module ./scripts/BuildOBS.psm1

          $vcpkgExe = Join-Path $env:GITHUB_WORKSPACE 'vcpkg' 'vcpkg'

          # Set PATH
          $env:PATH = @(
              Split-Path (Get-Command pwsh).Source -Parent
              '/opt/homebrew/opt/xcbeautify/bin:/usr/bin:/bin:/usr/sbin:/sbin'
          ) -join [System.IO.Path]::PathSeparator

          $env:PATH = @(
              Split-Path (& $vcpkgExe fetch cmake | Select-Object -Last 1) -Parent
              Split-Path (& $vcpkgExe fetch ninja | Select-Object -Last 1) -Parent
              $env:PATH
          ) -join [System.IO.Path]::PathSeparator

          # Remove vcpkg variables
          $env:VCPKG_ROOT = $null
          $env:VCPKG_INSTALLATION_ROOT = $null

          # Configure GITHUB_TOKEN
          $basicToken = [System.Convert]::ToBase64String(
              [System.Text.Encoding]::UTF8.GetBytes("x-access-token:$env:GITHUB_TOKEN")
          )

          Write-Output "::add-mask::$basicToken"

          $env:GIT_CONFIG_COUNT = '1'
          $env:GIT_CONFIG_KEY_0 = 'http.https://github.com/.extraHeader'
          $env:GIT_CONFIG_VALUE_0 = "Authorization: basic $basicToken"

          $assetSourceScript = Join-Path $env:GITHUB_WORKSPACE 'scripts' 'vcpkg_asset_sources.ps1'
          $env:X_VCPKG_ASSET_SOURCES = "clear;x-script,pwsh -NoProfile -ExecutionPolicy Bypass -File `"$assetSourceScript`" {url} {sha512} {dst}"

          # Build OBS
          Initialize-ObsDeps -Component prebuilt
          Initialize-ObsDeps -Component qt6
          Invoke-ObsConfigure
          Invoke-ObsBuild | tee build_obs.log | xcbeautify
          Install-Obs

      - name: Upload OBS build logs
        if: inputs.build-obs && always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build OBS logs
          path: |
            build_obs*.log
          if-no-files-found: ignore
          retention-days: 7

      - name: Install dependencies from vcpkg.json (arm64-osx-obs)
        if: inputs.install-vcpkg
        shell: pwsh
        env:
          VCPKG_ROOT: '${{ github.workspace }}/vcpkg'
        run: |
          Set-StrictMode -Version Latest; $ErrorActionPreference = 'Stop'; $PSNativeCommandUseErrorActionPreference = $true

          $vcpkgExe = Join-Path $env:VCPKG_ROOT 'vcpkg'

          $env:PATH = '/usr/bin:/bin:/usr/sbin:/sbin'

          & $vcpkgExe install --triplet=arm64-osx-obs --x-install-root=vcpkg_arm64_installed

      - name: Install dependencies from vcpkg.json (x64-osx-obs)
        if: inputs.install-vcpkg
        shell: pwsh
        env:
          VCPKG_ROOT: '${{ github.workspace }}/vcpkg'
        run: |
          Set-StrictMode -Version Latest; $ErrorActionPreference = 'Stop'; $PSNativeCommandUseErrorActionPreference = $true

          $vcpkgExe = Join-Path $env:VCPKG_ROOT 'vcpkg'

          $env:PATH = '/usr/bin:/bin:/usr/sbin:/sbin'

          & $vcpkgExe install --triplet=x64-osx-obs --x-install-root=vcpkg_x64_installed

      - name: Lipo vcpkg_installed
        if: inputs.install-vcpkg
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          ./scripts/lipo_vcpkg_macos.sh \
            ./vcpkg_installed/universal-osx-obs \
            ./vcpkg_arm64_installed/arm64-osx-obs \
            ./vcpkg_x64_installed/x64-osx-obs

      - name: Generate toolchain hash for building ONNX Runtime
        if: inputs.build-onnxruntime
        id: ort-toolchain-hash
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          HASH: >-
            ${{ hashFiles(
              'buildspec.props',
              'scripts/BuildOnnxRuntime.psm1',
              'src/required_operators_and_types.with_runtime_opt.config',
              'scripts/ort_patches/*.patch'
            ) }}
        run: |
          printf 'HASH=%s\n' "$HASH" >> "$GITHUB_OUTPUT"

      - name: Restore ONNX Runtime ccache
        if: inputs.build-onnxruntime
        id: restore-ccache-ort
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.ORT_CCACHE_DIR }}
          key: ccache-ort-${{ runner.os }}-universal-${{ steps.image-metadata.outputs.ImageVersion }}-${{ steps.ort-toolchain-hash.outputs.HASH }}-${{ steps.setup-ccache.outputs.VERSION }}
          restore-keys: |
            ccache-ort-${{ runner.os }}-universal-${{ steps.image-metadata.outputs.ImageVersion }}-${{ steps.ort-toolchain-hash.outputs.HASH }}-
            ccache-ort-${{ runner.os }}-universal-${{ steps.image-metadata.outputs.ImageVersion }}-
            ccache-ort-${{ runner.os }}-universal-

      - name: Reset ONNX Runtime ccache stats
        if: inputs.build-onnxruntime
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CCACHE_DIR: '${{ env.ORT_CCACHE_DIR }}'
        run: |
          ccache -z

      - name: Build ONNX Runtime (macOS)
        if: inputs.build-onnxruntime
        shell: pwsh
        env:
          CCACHE_BASEDIR: '${{ github.workspace }}'
          CCACHE_SLOPPINESS: include_file_mtime,time_macros
          GITHUB_TOKEN: '${{ github.token }}'
          PYTHON: ${{ steps.setup-python.outputs.python-path }}
          ORT_VERSION: ${{ steps.buildspec.outputs.onnxruntime_git_tag }}
        run: |
          Set-StrictMode -Version Latest; $ErrorActionPreference = 'Stop'; $PSNativeCommandUseErrorActionPreference = $true; $ProgressPreference = 'SilentlyContinue'

          Import-Module ./scripts/BuildOnnxRuntime.psm1

          $vcpkgOrtRoot = Join-Path $env:GITHUB_WORKSPACE 'vcpkg_ort'

          # Set PATH
          $env:PATH = @(
              Split-Path (Get-Command ccache).Source -Parent
              '/opt/homebrew/opt/xcbeautify/bin:/usr/bin:/bin:/usr/sbin:/sbin'
          ) -join [System.IO.Path]::PathSeparator

          $env:PATH = @(
              Split-Path (Get-OrtToolchain -VcpkgRoot $vcpkgOrtRoot -Name cmake) -Parent
              Split-Path (Get-OrtToolchain -VcpkgRoot $vcpkgOrtRoot -Name ninja) -Parent
              $env:PATH
          ) -join [System.IO.Path]::PathSeparator

          # Remove vcpkg variables
          $env:VCPKG_ROOT = $null
          $env:VCPKG_INSTALLATION_ROOT = $null

          # Configure GITHUB_TOKEN
          $basicToken = [System.Convert]::ToBase64String(
              [System.Text.Encoding]::UTF8.GetBytes("x-access-token:$env:GITHUB_TOKEN")
          )

          Write-Output "::add-mask::$basicToken"

          $env:GIT_CONFIG_COUNT = '1'
          $env:GIT_CONFIG_KEY_0 = 'http.https://github.com/.extraHeader'
          $env:GIT_CONFIG_VALUE_0 = "Authorization: basic $basicToken"

          $assetSourceScript = Join-Path $env:GITHUB_WORKSPACE 'scripts' 'vcpkg_asset_sources.ps1'
          $env:X_VCPKG_ASSET_SOURCES = "clear;x-script,pwsh -NoProfile -ExecutionPolicy Bypass -File `"$assetSourceScript`" {url} {sha512} {dst}"

          # Build ONNX Runtime
          Update-OrtSourceWithPatches -OrtVersion $env:ORT_VERSION
          Invoke-OrtBuildPy -Command update -OsxArchitectures arm64 -OsxDeploymentTarget $env:OSX_DEPLOYMENT_TARGET
          Invoke-OrtBuildPy -Command update -OsxArchitectures x86_64 -OsxDeploymentTarget $env:OSX_DEPLOYMENT_TARGET
          Invoke-OrtBuildPy -Command build -OsxArchitectures arm64 -OsxDeploymentTarget $env:OSX_DEPLOYMENT_TARGET | tee build_onnxruntime_arm64.log | xcbeautify
          Invoke-OrtBuildPy -Command build -OsxArchitectures x86_64 -OsxDeploymentTarget $env:OSX_DEPLOYMENT_TARGET | tee build_onnxruntime_x86_64.log | xcbeautify
          Install-Ort

      - name: Lipo ORT vcpkg_installed
        if: inputs.build-onnxruntime
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          ./scripts/lipo_vcpkg_macos.sh \
            ./vcpkg_ort_installed/universal-osx \
            ./build_ort_arm64/Release/vcpkg_installed/arm64-osx \
            ./build_ort_x86_64/Release/vcpkg_installed/x64-osx

      - name: Save ONNX Runtime ccache
        if: inputs.build-onnxruntime
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.ORT_CCACHE_DIR }}
          key: ${{ steps.restore-ccache-ort.outputs.cache-primary-key }}

      - name: Upload ONNX Runtime build logs
        if: inputs.build-onnxruntime && always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build ONNX Runtime logs
          path: |
            build_onnxruntime*.log
          if-no-files-found: ignore
          retention-days: 7

      - name: Show ONNX Runtime ccache stats
        if: inputs.build-onnxruntime && always()
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CCACHE_DIR: '${{ env.ORT_CCACHE_DIR }}'
        run: |
          printf '## ccache stats for ONNX Runtime (macOS)\n\n```\n%s```\n' "$(ccache -s)" >> "$GITHUB_STEP_SUMMARY"

      - name: Build Plugin (macOS)
        if: inputs.build-obs && inputs.build-onnxruntime
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest; $ErrorActionPreference = 'Stop'; $PSNativeCommandUseErrorActionPreference = $true

          $vcpkgExe = Join-Path $env:GITHUB_WORKSPACE 'vcpkg' 'vcpkg'

          # Set PATH
          $env:PATH = @(
              Split-Path (Get-Command xcbeautify).Source -Parent
              '/usr/bin:/bin:/usr/sbin:/sbin'
          ) -join [System.IO.Path]::PathSeparator

          $env:PATH = @(
              Split-Path (& $vcpkgExe fetch cmake | Select-Object -Last 1) -Parent
              Split-Path (& $vcpkgExe fetch ninja | Select-Object -Last 1) -Parent
              $env:PATH
          ) -join [System.IO.Path]::PathSeparator

          cmake --preset macos -G Xcode -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build --preset macos --config RelWithDebInfo | tee build_plugin.log | xcbeautify

      - name: Upload Plugin build logs
        if: inputs.build-obs && inputs.build-onnxruntime && always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build Plugin logs
          path: |
            build_plugin*.log
          if-no-files-found: ignore
          retention-days: 7

      - name: Install Plugin into stage
        if: inputs.build-obs && inputs.build-onnxruntime
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          cmake --install build --config RelWithDebInfo --strip --prefix build_stage

      - name: Extract dSYM
        if: inputs.build-obs && inputs.build-onnxruntime
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          mkdir -p release
          . ./build/cmake_export.sh

          dsymutil "build/RelWithDebInfo/$PLUGIN_NAME.plugin/Contents/MacOS/$PLUGIN_NAME" -o "build/$PLUGIN_NAME.dSYM"
          ZSTD_CLEVEL=19 tar -acf "release/$PLUGIN_NAME.dSYM.tar.zst" --mac-metadata "build/$PLUGIN_NAME.dSYM"

      - name: Set up macOS Signing Certificates
        if: inputs.build-obs && inputs.build-onnxruntime && inputs.environment == 'production-macos'
        id: codesign
        uses: ./.github/actions/setup-macos-codesigning
        with:
          MACOS_SIGNING_APPLICATION_IDENTITY: ${{ secrets.MACOS_SIGNING_APPLICATION_IDENTITY }}
          MACOS_SIGNING_CERT: ${{ secrets.MACOS_SIGNING_CERT }}
          MACOS_SIGNING_CERT_PASSWORD: ${{ secrets.MACOS_SIGNING_CERT_PASSWORD }}

      - name: Package Plugin (macOS)
        if: inputs.build-obs && inputs.build-onnxruntime
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CODESIGN_ENABLED: "${{ inputs.environment == 'production-macos' }}"
          MACOS_SIGNING_APPLICATION_IDENTITY: ${{ secrets.MACOS_SIGNING_APPLICATION_IDENTITY }}
          MACOS_SIGNING_INSTALLER_IDENTITY: ${{ secrets.MACOS_SIGNING_INSTALLER_IDENTITY }}
        run: |
          mkdir -p release
          . ./build/cmake_export.sh

          PLUGIN_BUNDLE="build_stage/Library/Application Support/obs-studio/plugins/$PLUGIN_NAME.plugin"

          if [[ "$CODESIGN_ENABLED" == true ]]; then
            codesign -s "$MACOS_SIGNING_APPLICATION_IDENTITY" -f --deep --options runtime --timestamp "$PLUGIN_BUNDLE"
          fi

          pkgbuild \
            --root build_stage \
            --identifier "$PLUGIN_BUNDLE_ID" \
            --version "$PLUGIN_VERSION" \
            --install-location / \
            build/component.pkg

          if [[ "$CODESIGN_ENABLED" == true ]]; then
            productbuild \
              --distribution build/Distribution \
              --package-path build \
              --resources . \
              --sign "$MACOS_SIGNING_INSTALLER_IDENTITY" \
              "release/$PLUGIN_NAME-$PLUGIN_VERSION-macos-universal.pkg"
          else
            productbuild \
              --distribution build/Distribution \
              --package-path build \
              --resources . \
              "release/$PLUGIN_NAME-$PLUGIN_VERSION-macos-universal.pkg"
          fi

      - name: Notarize Installer
        if: inputs.build-obs && inputs.build-onnxruntime && inputs.environment == 'production-macos'
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          CODESIGN_TEAM: '${{ steps.codesign.outputs.CODESIGN_TEAM }}'
          MACOS_NOTARIZATION_PASSWORD: '${{ secrets.MACOS_NOTARIZATION_PASSWORD }}'
          MACOS_NOTARIZATION_USERNAME: '${{ secrets.MACOS_NOTARIZATION_USERNAME }}'
        run: |
          . ./build/cmake_export.sh

          xcrun notarytool submit "release/$PLUGIN_NAME-$PLUGIN_VERSION-macos-universal.pkg" \
            --apple-id "$MACOS_NOTARIZATION_USERNAME" \
            --password "$MACOS_NOTARIZATION_PASSWORD" \
            --team-id "$CODESIGN_TEAM" \
            --wait

          xcrun stapler staple "release/$PLUGIN_NAME-$PLUGIN_VERSION-macos-universal.pkg"

      - name: Upload Plugin Binary
        if: inputs.build-obs && inputs.build-onnxruntime
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pluginbinary-${{ runner.os }}-universal-${{ github.run_id }}
          path: |
            release/*.pkg
            release/*.dSYM.tar.zst
          if-no-files-found: error
          retention-days: 7
