# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Plugin CI

# file: .github/workflows/plugin.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-05-28

on:
  pull_request:
    branches: [main]
  merge_group:
  push:
    branches: [main]
    tags: ['*']
  schedule:
    - cron: 14 3 * * *
  workflow_dispatch:
    inputs:
      build-obs:
        description: Flag to build OBS Studio.
        required: false
        type: boolean
        default: true
      install-vcpkg:
        description: Flag to install vcpkg dependencies.
        required: false
        type: boolean
        default: true
      build-onnxruntime:
        description: Flag to build ONNX Runtime.
        required: false
        type: boolean
        default: true

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-config:
    permissions:
      contents: read
    uses: ./.github/workflows/ci-config.yml

  build-windows:
    needs: ci-config
    permissions:
      contents: read
    uses: ./.github/workflows/plugin-build-windows.yml
    with:
      job-index: 0
      runs-on: windows-2022
      WINDOWS_SDK_VERSION: ${{ needs.ci-config.outputs.WINDOWS_SDK_VERSION }}
      VCPKG_BINARY_SOURCES: ${{ needs.ci-config.outputs.VCPKG_BINARY_SOURCES }}
      build-obs: ${{ github.event_name != 'workflow_dispatch' || inputs.build-obs }}
      install-vcpkg: ${{ github.event_name != 'workflow_dispatch' || inputs.install-vcpkg }}
      build-onnxruntime: ${{ github.event_name != 'workflow_dispatch' || inputs.build-onnxruntime }}

  build-macos:
    needs: ci-config
    permissions:
      contents: read
    uses: ./.github/workflows/plugin-build-macos.yml
    with:
      job-index: 0
      runs-on: macos-15
      DEVELOPER_DIR: /Applications/Xcode_16.4.app
      OSX_DEPLOYMENT_TARGET: ${{ needs.ci-config.outputs.OSX_DEPLOYMENT_TARGET }}
      VCPKG_BINARY_SOURCES: ${{ needs.ci-config.outputs.VCPKG_BINARY_SOURCES }}
      build-obs: ${{ github.event_name != 'workflow_dispatch' || inputs.build-obs }}
      install-vcpkg: ${{ github.event_name != 'workflow_dispatch' || inputs.install-vcpkg }}
      build-onnxruntime: ${{ github.event_name != 'workflow_dispatch' || inputs.build-onnxruntime }}
    secrets: inherit

  build-debian:
    strategy:
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm]
    permissions:
      contents: read
    uses: ./.github/workflows/plugin-build-debian.yml
    with:
      job-index: 0
      runs-on: ${{ matrix.runs-on }}
      image: debian:forky

  # build-ubuntu:
  #   needs: ci-config
  #   permissions:
  #     contents: read
  #   uses: ./.github/workflows/plugin-build-ubuntu.yml
  #   with:
  #     VCPKG_BINARY_SOURCES: ${{ needs.config.outputs.VCPKG_BINARY_SOURCES }}
  #     vcpkg-version: ${{ needs.config.outputs.VCPKG_VERSION }}
  #     ort-version: ${{ needs.config.outputs.ORT_VERSION }}

  accept-plugin:
    name: Accept Plugin CI
    needs:
      - build-windows
      - build-macos
      - build-debian
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Check workflow results
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          BUILD_WINDOWS_RESULT: ${{ needs.build-windows.result }}
          BUILD_MACOS_RESULT: ${{ needs.build-macos.result }}
        run: |
          [[ "$BUILD_WINDOWS_RESULT" == 'success' ]] && [[ "$BUILD_MACOS_RESULT" == 'success' ]]

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: accept-plugin
    permissions:
      artifact-metadata: write
      attestations: write
      contents: write
      id-token: write
    uses: ./.github/workflows/plugin-release.yml
