# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: PR Check

on:
  pull_request:

permissions: {}

concurrency:
  group: pr-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows-x64:
    uses: ./.github/workflows/build-windows.yml
    permissions:
      contents: read
    with:
      attest-artifacts: false
      release-build: false
      runs-on: windows-2025-vs2026

  build-macos:
    uses: ./.github/workflows/build-macos.yml
    permissions:
      contents: read
    with:
      attest-artifacts: false
      release-build: false
      TAHOE_DEVELOPER_DIR: /Applications/Xcode_26.5.app

  build-debian-amd64:
    uses: ./.github/workflows/build-debian.yml
    permissions:
      contents: read
    with:
      attest-artifacts: false
      arm64: false
      release-build: false

  build-debian-arm64:
    uses: ./.github/workflows/build-debian.yml
    permissions:
      contents: read
    with:
      attest-artifacts: false
      arm64: true
      release-build: false

  build-ubuntu-amd64:
    uses: ./.github/workflows/build-ubuntu.yml
    permissions:
      contents: read
    with:
      attest-artifacts: false
      arm64: false
      release-build: false

  build-ubuntu-arm64:
    uses: ./.github/workflows/build-ubuntu.yml
    permissions:
      contents: read
    with:
      attest-artifacts: false
      arm64: true
      release-build: false

  build-arch:
    uses: ./.github/workflows/build-arch.yml
    permissions:
      contents: read
    with:
      release-build: false

  accept-pr-check:
    if: always()
    needs:
      - build-arch
      - build-debian-amd64
      - build-debian-arm64
      - build-macos
      - build-ubuntu-amd64
      - build-ubuntu-arm64
      - build-windows-x64
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions: {}
    steps:
      - name: Check workflow results
        env:
          NEEDS: ${{ toJSON(needs) }}
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: jq -e 'all(.[]; .result == "success")' <<< "${NEEDS:?}"
