# SPDX-FileCopyrightText: 2018-2026 OBS Project and its contributors
# SPDX-FileCopyrightText: 2021-2026 Roy Shilkrot <roy.shil@gmail.com>
# SPDX-FileCopyrightText: 2023-2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Push
run-name: ${{ github.ref_name }} push run 🚀
on:
  push:
    branches:
      - main
    tags:
      - '*'
permissions:
  contents: write
jobs:
  check-format:
    name: Check Formatting 🔍
    if: github.ref_name == 'master' || github.ref_name == 'main'
    uses: ./.github/workflows/check-format.yaml
    permissions:
      contents: read

  build-project:
    name: Build Project 🧱
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  create-release:
    name: Create Release 🛫
    if: github.ref_type == 'tag'
    runs-on: ubuntu-24.04
    needs: build-project
    defaults:
      run:
        shell: bash
    permissions:
      attestations: write
      contents: write
      id-token: write
    steps:
      - name: Check Release Tag ☑️
        id: check
        run: |
          : Check Release Tag ☑️
          if [[ "${RUNNER_DEBUG}" ]]; then set -x; fi
          shopt -s extglob

          case "${GITHUB_REF_NAME}" in
            +([0-9]).+([0-9]).+([0-9]) )
              echo 'validTag=true' >> $GITHUB_OUTPUT
              echo 'prerelease=false' >> $GITHUB_OUTPUT
              echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
              ;;
            +([0-9]).+([0-9]).+([0-9])-@(beta|rc)*([0-9]) )
              echo 'validTag=true' >> $GITHUB_OUTPUT
              echo 'prerelease=true' >> $GITHUB_OUTPUT
              echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
              ;;
            *) echo 'validTag=false' >> $GITHUB_OUTPUT ;;
          esac

      - name: Download Build Artifacts 📥
        uses: actions/download-artifact@v4
        if: fromJSON(steps.check.outputs.validTag)
        id: download

      - name: Rename Files 🏷️
        if: fromJSON(steps.check.outputs.validTag)
        run: |
          : Rename Files 🏷️
          if [[ "${RUNNER_DEBUG}" ]]; then set -x; fi
          shopt -s extglob
          shopt -s nullglob

          root_dir="$(pwd)"
          commit_hash="${GITHUB_SHA:0:9}"

          variants=(
            'windows-x64;zip|exe'
            'macos-universal;tar.xz|pkg'
            'ubuntu-24.04-x86_64;tar.xz|deb|ddeb'
          )

          for variant_data in "${variants[@]}"; do
            IFS=';' read -r variant suffix <<< "${variant_data}"

            candidates=(*-${variant}-${commit_hash}/@(*|*-dbgsym).@(${suffix}))

            for candidate in "${candidates[@]}"; do
              mv "${candidate}" "${root_dir}"
            done
          done

      - name: Attest build artifacts
        if: fromJSON(steps.check.outputs.validTag)
        id: attest
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: ${{ github.workspace }}/*

      - name: Create Draft Release
        if: fromJSON(steps.check.outputs.validTag)
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.check.outputs.version }}
        run: |
          set -euo pipefail
          shopt -s extglob nullglob

          ASSETS=(
            *.zip
            *.pkg
            *.deb
            *.ddeb
          )

          CREATE_RELEASE_FLAGS=(
            --draft
            --generate-notes
            --title "$TAG_NAME"
            --verify-tag
          )

          if [[ "$TAG_NAME" == *"-"* ]]; then
            CREATE_RELEASE_FLAGS+=(--prerelease)
          fi

          gh release create "$TAG_NAME" "${ASSETS[@]}" "${CREATE_RELEASE_FLAGS[@]}"
