# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

# file: .github/workflows/scripts.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# date: 2026-05-23

name: Scripts CI

on:
  pull_request:
    branches: [main]
  merge_group:
  push:
    branches: [main]
    tags: ['*']

permissions: {}

jobs:
  build-deb:
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        image:
          - debian:forky-slim
          - ubuntu:resolute

    name: ${{ matrix.image }} (${{ contains(matrix.runs-on, 'arm') && 'arm64' || 'x64' }})
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 180

    permissions:
      contents: read

    container:
      image: ${{ matrix.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Bootstrap, Setup, and Build
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          bin/bootstrap
          bin/setup
          bin/build

      - name: Install
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          dpkg -i release/obs-backgroundremoval-*-linux-gnu.deb
          dpkg -l obs-backgroundremoval
